-- Real rank data scraped from https://crossfire.z8games.com/ranks.html
-- Run this in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/qywburkldwdkegztsgjj/editor
-- Last updated: 2026-07-22

-- Clear existing ranks
DELETE FROM ranks;

-- Insert all 101 real ranks
INSERT INTO ranks (tier, name, exp_required, bonus, image_url) VALUES
(1,   'Trainee 1',              0,         '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_1.jpg'),
(2,   'Trainee 2',              457,       'Smile Grenade 7 days',               'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_2.jpg'),
(3,   'Private',                913,       'Boost Box 3 days',                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_3.jpg'),
(4,   'Private First Class',    1825,      'Starter Weapon Box 3 days',          'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_4.jpg'),
(5,   'Corporal',               3193,      'Pottery Boost Box 7 days',           'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_5.jpg'),
(6,   'Sergeant 1',             5017,      'Camo Box 7 days',                    'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_6.jpg'),
(7,   'Sergeant 2',             7297,      '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_7.jpg'),
(8,   'Sergeant 3',             10033,     '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_8.jpg'),
(9,   'Sergeant 4',             13225,     '30,000 GP',                          'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_9.jpg'),
(10,  'Staff Sergeant 1',       17785,     'Red Dragon Box 7 days',              'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_10.jpg'),
(11,  'Staff Sergeant 2',       23941,     '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_11.jpg'),
(12,  'Staff Sergeant 3',       33061,     '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_12.jpg'),
(13,  'Staff Sergeant 4',       43093,     'VIP Weapon Box 3 days',              'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_13.jpg'),
(14,  'Staff Sergeant 5',       54037,     '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_14.jpg'),
(15,  'Staff Sergeant 6',       65893,     'Red SMOKE 30 days',                  'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_15.jpg'),
(16,  'Sergeant First Class 1', 78661,     '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_16.jpg'),
(17,  'Sergeant First Class 2', 92341,     '30,000 GP',                          'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_17.jpg'),
(18,  'Sergeant First Class 3', 106933,    '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_18.jpg'),
(19,  'Sergeant First Class 4', 122437,    'AK-47-K-Yellow Fractal 14 days',     'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_19.jpg'),
(20,  'Sergeant First Class 5', 138853,    '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_20.jpg'),
(21,  'Sergeant First Class 6', 156181,    'B.C-Axe-Ares 7 days',               'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_21.jpg'),
(22,  'Master Sergeant 1',      174421,    '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_22.jpg'),
(23,  'Master Sergeant 2',      193573,    'M4A1-S-Yellow Fractal 14 days',      'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_23.jpg'),
(24,  'Master Sergeant 3',      213637,    '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_24.jpg'),
(25,  'Master Sergeant 4',      234613,    'Barrett M82A1-Royal Dragon 7 days',  'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_25.jpg'),
(26,  'Master Sergeant 5',      256501,    '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_26.jpg'),
(27,  'Master Sergeant 6',      279301,    'Sidearm Box 7 days',                 'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_27.jpg'),
(28,  'Second Lieutenant 1',    326725,    '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_28.jpg'),
(29,  'Second Lieutenant 2',    375973,    'M4A1-S-Yellow Fractal 30 days',      'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_29.jpg'),
(30,  'Second Lieutenant 3',    427045,    '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_30.jpg'),
(31,  'Second Lieutenant 4',    479941,    'Throw Weapon Box 30 days',           'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_31.jpg'),
(32,  'Second Lieutenant 5',    534661,    '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_32.jpg'),
(33,  'Second Lieutenant 6',    591205,    'KAC Chainsaw-Ancient Dragon 30 days','https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_33.jpg'),
(34,  'Second Lieutenant 7',    649573,    '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_34.jpg'),
(35,  'Second Lieutenant 8',    709765,    'Kukri-Royal Dragon 30 days',         'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_35.jpg'),
(36,  'First Lieutenant 1',     771781,    '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_36.jpg'),
(37,  'First Lieutenant 2',     835621,    'AK-47-K-Yellow Fractal 30 days',     'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_37.jpg'),
(38,  'First Lieutenant 3',     901285,    '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_38.jpg'),
(39,  'First Lieutenant 4',     968773,    'Bulletproof Package 30 days',        'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_39.jpg'),
(40,  'First Lieutenant 5',     1038085,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_40.jpg'),
(41,  'First Lieutenant 6',     1109221,   'Rifle Box 30 days',                  'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_41.jpg'),
(42,  'First Lieutenant 7',     1182181,   'Blue Muzzle Flame 30 days',          'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_42.jpg'),
(43,  'First Lieutenant 8',     1256965,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_43.jpg'),
(44,  'Captain 1',              1333573,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_44.jpg'),
(45,  'Captain 2',              1412005,   '30,000 GP',                          'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_45.jpg'),
(46,  'Captain 3',              1492261,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_46.jpg'),
(47,  'Captain 4',              1574341,   'CFWE Pistol Ticket 30 days',         'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_47.jpg'),
(48,  'Captain 5',              1658245,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_48.jpg'),
(49,  'Captain 6',              1743973,   'Yellow Smoke 30 days',               'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_49.jpg'),
(50,  'Captain 7',              1831525,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_50.jpg'),
(51,  'Captain 8',              1920901,   'Green Muzzle Flame 30 days',         'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_51.jpg'),
(52,  'Major 1',                2057701,   '30,000 GP',                          'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_52.jpg'),
(53,  'Major 2',                2107237,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_53.jpg'),
(54,  'Major 3',                2339509,   'Mutant Box 30 days',                 'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_54.jpg'),
(55,  'Major 4',                2484517,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_55.jpg'),
(56,  'Major 5',                2632261,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_56.jpg'),
(57,  'Major 6',                2782741,   'CFWE Sniper Ticket 30 days',         'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_57.jpg'),
(58,  'Major 7',                2935957,   'Octane Camo Grenade 30 days',        'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_58.jpg'),
(59,  'Major 8',                3091909,   'CFWE MG Ticket 30 days',             'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_59.jpg'),
(60,  'Lieutenant Colonel 1',   3277045,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_60.jpg'),
(61,  'Lieutenant Colonel 2',   3465373,   'Bulletproof Package 30 days',        'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_61.jpg'),
(62,  'Lieutenant Colonel 3',   3673537,   'CFWE SMG Ticket 30 days',            'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_62.jpg'),
(63,  'Lieutenant Colonel 4',   3885178,   'M4A1 Custom-Octane Camo 30 days',    'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_63.jpg'),
(64,  'Lieutenant Colonel 5',   4100296,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_64.jpg'),
(65,  'Lieutenant Colonel 6',   4318891,   'CFWE Rifle Ticket 30 days',          'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_65.jpg'),
(66,  'Lieutenant Colonel 7',   4540963,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_66.jpg'),
(67,  'Lieutenant Colonel 8',   4766512,   '10 Horus Crates',                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_67.jpg'),
(68,  'Colonel 1',              5028199,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_68.jpg'),
(69,  'Colonel 2',              5319184,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_69.jpg'),
(70,  'Colonel 3',              5614501,   'M4A1-S-Yellow Fractal 60 days',      'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_70.jpg'),
(71,  'Colonel 4',              5914150,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_71.jpg'),
(72,  'Colonel 5',              6218131,   'BC Axe-Octane Camo 30 days',         'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_72.jpg'),
(73,  'Colonel 6',              6526501,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_73.jpg'),
(74,  'Colonel 7',              6839203,   'Character Box 30 days',              'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_74.jpg'),
(75,  'Colonel 8',              7156237,   '10 Octane Crates',                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_75.jpg'),
(76,  'Brigadier General 1',    7578037,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_76.jpg'),
(77,  'Brigadier General 2',    8026912,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_77.jpg'),
(78,  'Brigadier General 3',    8481772,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_78.jpg'),
(79,  'Brigadier General 4',    8964562,   'AK-47-K-Yellow Fractal 60 days',     'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_79.jpg'),
(80,  'Brigadier General 5',    9475852,   '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_80.jpg'),
(81,  'Brigadier General 6',    10016212,  '30 x 7th Anniversary Crates',        'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_81.jpg'),
(82,  'Major General 1',        10586212,  '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_82.jpg'),
(83,  'Major General 2',        11186422,  'G-Yellow Crystal perm',              'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_83.jpg'),
(84,  'Major General 3',        11817412,  '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_84.jpg'),
(85,  'Major General 4',        12479752,  '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_85.jpg'),
(86,  'Major General 5',        13174012,  '10 Color Blaze Crates',              'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_86.jpg'),
(87,  'Major General 6',        13900762,  'Slaughter Ticket Box',               'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_87.jpg'),
(88,  'Lieutenant General 1',   14660572,  '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_88.jpg'),
(89,  'Lieutenant General 2',   15454012,  '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_89.jpg'),
(90,  'Lieutenant General 3',   16281652,  'M4A1-S-Yellow Fractal perm',         'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_90.jpg'),
(91,  'Lieutenant General 4',   17144062,  '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_91.jpg'),
(92,  'Lieutenant General 5',   18041812,  '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_92.jpg'),
(93,  'Lieutenant General 6',   18975472,  'RPK-Infernal Dragon 30 days',        'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_93.jpg'),
(94,  'General 1',              19945612,  '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_94.jpg'),
(95,  'General 2',              20952802,  'AK-47-K-Yellow Fractal perm',        'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_95.jpg'),
(96,  'General 3',              21997612,  '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_96.jpg'),
(97,  'General 4',              23080612,  'AWM-Infernal Dragon 30 days',        'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_97.jpg'),
(98,  'General 5',              24202372,  '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_98.jpg'),
(99,  'General 6',              25363462,  'AK-47 Fury 30 days',                 'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_99.jpg'),
(100, 'Marshall',               26564452,  '',                                   'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_100.jpg'),
(104, 'Grand Marshall',         100000000, '30 Free Crate Tickets',              'https://z8games.akamaized.net/cfna/templates/assets/imgs/rank_104.jpg');
