// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage/NeonOps.tsx": () => import("../components/mockups/homepage/NeonOps.tsx"),
  "./components/mockups/homepage/TacticalDark.tsx": () => import("../components/mockups/homepage/TacticalDark.tsx")
};
