export type WestRecentWeapon = {
  id: string;
  name: string;
  nameAr: string;
  category: string;
  categoryAr: string;
  releaseDate: string;
  releaseName: string;
  releaseNameAr: string;
  imageUrl: string;
  imageKind: "catalogue" | "release-artwork";
  sourceUrl: string;
  sourceLabel: string;
  availabilityEn: string;
  availabilityAr: string;
  descriptionEn: string;
  descriptionAr: string;
  verificationEn: string;
  verificationAr: string;
};

const ROADMAP_BASE = "https://z8games.akamaized.net/cfna/patches/2026/img";
const CATALOGUE_BASE = "https://z8games.akamaized.net/cfna/web/inventory/weapons/540_400";

const alt4Artwork = `${ROADMAP_BASE}/260806_cfwe_rubycrates_roadmapthumb_weapons.jpg`;
const equinoxArtwork = `${ROADMAP_BASE}/260716_cfwe_sapphire_RSL_roadmapthumb.jpg`;

const alt4DescriptionEn =
  "A named weapon in the official ALT+F4 release group. Z8Games describes the collection as blacked-out weapons streaked with pink and white, stamped with ALT F4, and available for a limited time in the Garnet Crate in the Black Market.";
const alt4DescriptionAr =
  "سلاح مستقل ضمن مجموعة ALT+F4 الرسمية. تصف Z8Games المجموعة بأنها أسلحة سوداء بخطوط وردية وبيضاء تحمل علامة ALT F4، وكانت متاحة لفترة محدودة داخل Garnet Crate في السوق السوداء.";
const alt4AvailabilityEn =
  "Limited-time Garnet Crate in the Black Market; collecting the full ALT+F4 set grants an exclusive namecard.";
const alt4AvailabilityAr =
  "متاح لفترة محدودة داخل Garnet Crate في السوق السوداء؛ جمع مجموعة ALT+F4 كاملة يمنح بطاقة اسم حصرية.";

const equinoxDescriptionEn =
  "A named weapon in the official Equinox Lily release group. The publisher describes the Lapis Prospect design as mystical Red Spider Lily artwork representing death, separation, and the boundary between life and the afterlife.";
const equinoxDescriptionAr =
  "سلاح مستقل ضمن مجموعة Equinox Lily الرسمية. تصف الشركة تصميم Lapis Prospect بأنه مزين بزهور زنبق العنكبوت الأحمر، في إشارة إلى الموت والفراق والحد الفاصل بين الحياة وما بعدها.";
const equinoxAvailabilityEn =
  "Limited-time Lapis Prospect in the Black Market; collecting the complete Equinox Lily set grants an exclusive namecard.";
const equinoxAvailabilityAr =
  "متاح لفترة محدودة داخل Lapis Prospect في السوق السوداء؛ جمع مجموعة Equinox Lily كاملة يمنح بطاقة اسم حصرية.";

const roadmapSource = "https://crossfire.z8games.com/patches/2026";
const catalogueSource = "https://crossfire.z8games.com/weapons.html";
const inventorySource = "https://crossfire.z8games.com/profile/9396634/inventory";

export const WEST_RECENT_WEAPONS: WestRecentWeapon[] = [
  {
    id: "west-m4a1-s-iron-alt4",
    name: "M4A1-S-Iron ALT+F4",
    nameAr: "M4A1-S-Iron ALT+F4",
    category: "Assault Rifle",
    categoryAr: "بندقية هجومية",
    releaseDate: "2026-08-12",
    releaseName: "ALT+F4 Weapons",
    releaseNameAr: "أسلحة ALT+F4",
    imageUrl: "https://z8games.akamaized.net/cfna/web/inventory/weapons/300_169/W9964.png",
    imageKind: "catalogue",
    sourceUrl: inventorySource,
    sourceLabel: "Z8Games public inventory record",
    availabilityEn: "Listed as an individual ALT+F4 item in a public Z8Games inventory record; the August roadmap identifies the release group and date.",
    availabilityAr: "مدرج كسجل فردي من ALT+F4 في مخزون عام على Z8Games؛ وتحدد خارطة طريق أغسطس مجموعة الإصدار وتاريخها.",
    descriptionEn: "M4A1-S-Iron ALT+F4 is represented by its own first-party CDN render rather than the grouped roadmap artwork. No unverified gameplay statistics are added.",
    descriptionAr: "يظهر M4A1-S-Iron ALT+F4 بصورة CDN رسمية مستقلة بدل صورة خارطة الطريق المجمعة. لا تتم إضافة إحصاءات لعب غير موثقة.",
    verificationEn: "Name and individual image verified on the public Z8Games inventory page; release group cross-checked against the official 2026 roadmap.",
    verificationAr: "تم التحقق من الاسم والصورة الفردية في صفحة مخزون Z8Games العامة، مع مطابقة مجموعة الإصدار مع خارطة الطريق الرسمية لعام 2026.",
  },
  {
    id: "west-awm-alt4-ironhawk",
    name: "AWM-ALT+F4 Ironhawk",
    nameAr: "AWM-ALT+F4 Ironhawk",
    category: "Sniper Rifle",
    categoryAr: "بندقية قنص",
    releaseDate: "2026-08-12",
    releaseName: "ALT+F4 Weapons",
    releaseNameAr: "أسلحة ALT+F4",
    imageUrl: "https://z8games.akamaized.net/cfna/web/inventory/weapons/300_169/W9962.png",
    imageKind: "catalogue",
    sourceUrl: inventorySource,
    sourceLabel: "Z8Games public inventory record",
    availabilityEn: "Listed as an individual ALT+F4 item in a public Z8Games inventory record; the August roadmap identifies the release group and date.",
    availabilityAr: "مدرج كسجل فردي من ALT+F4 في مخزون عام على Z8Games؛ وتحدد خارطة طريق أغسطس مجموعة الإصدار وتاريخها.",
    descriptionEn: "AWM-ALT+F4 Ironhawk has its own first-party CDN render in the public inventory record. The archive keeps the official name and does not infer damage or scope statistics.",
    descriptionAr: "يمتلك AWM-ALT+F4 Ironhawk صورة CDN رسمية مستقلة في سجل المخزون العام. يحتفظ الأرشيف بالاسم الرسمي دون استنتاج إحصاءات الضرر أو المنظار.",
    verificationEn: "Name and individual image verified on the public Z8Games inventory page; release group cross-checked against the official 2026 roadmap.",
    verificationAr: "تم التحقق من الاسم والصورة الفردية في صفحة مخزون Z8Games العامة، مع مطابقة مجموعة الإصدار مع خارطة الطريق الرسمية لعام 2026.",
  },
  {
    id: "west-hk417-elite-alt4",
    name: "HK417-Elite -ALT+F4",
    nameAr: "HK417-Elite -ALT+F4",
    category: "Assault Rifle",
    categoryAr: "بندقية هجومية",
    releaseDate: "2026-08-12",
    releaseName: "ALT+F4 Weapons",
    releaseNameAr: "أسلحة ALT+F4",
    imageUrl: alt4Artwork,
    imageKind: "release-artwork",
    sourceUrl: roadmapSource,
    sourceLabel: "Z8Games 2026 roadmap",
    availabilityEn: alt4AvailabilityEn,
    availabilityAr: alt4AvailabilityAr,
    descriptionEn: alt4DescriptionEn,
    descriptionAr: alt4DescriptionAr,
    verificationEn: "The individual name was captured from the official ALT+F4 roadmap detail modal. An individual public inventory render was not confirmed for this record, so the grouped release artwork is labeled explicitly.",
    verificationAr: "تم التقاط الاسم الفردي من نافذة تفاصيل تحديث ALT+F4 الرسمية. لم يتم تأكيد صورة فردية له في المخزون العام، لذلك تم توضيح أن الصورة هي صورة الإصدار المجمعة.",
  },
  {
    id: "west-kinetics-cpw-alt4",
    name: "Kinetics CPW-ALT+F4",
    nameAr: "Kinetics CPW-ALT+F4",
    category: "SMG",
    categoryAr: "رشاش خفيف",
    releaseDate: "2026-08-12",
    releaseName: "ALT+F4 Weapons",
    releaseNameAr: "أسلحة ALT+F4",
    imageUrl: "https://z8games.akamaized.net/cfna/web/inventory/weapons/300_169/W9960.png",
    imageKind: "catalogue",
    sourceUrl: inventorySource,
    sourceLabel: "Z8Games public inventory record",
    availabilityEn: "Listed as an individual ALT+F4 item in a public Z8Games inventory record; the August roadmap identifies the release group and date.",
    availabilityAr: "مدرج كسجل فردي من ALT+F4 في مخزون عام على Z8Games؛ وتحدد خارطة طريق أغسطس مجموعة الإصدار وتاريخها.",
    descriptionEn: "Kinetics CPW-ALT+F4 is represented by an individual first-party CDN render. The archive records the weapon name without adding unsupported performance claims.",
    descriptionAr: "يظهر Kinetics CPW-ALT+F4 بصورة CDN رسمية مستقلة. يسجل الأرشيف اسم السلاح دون إضافة ادعاءات أداء غير مدعومة.",
    verificationEn: "Name and individual image verified on the public Z8Games inventory page; release group cross-checked against the official 2026 roadmap.",
    verificationAr: "تم التحقق من الاسم والصورة الفردية في صفحة مخزون Z8Games العامة، مع مطابقة مجموعة الإصدار مع خارطة الطريق الرسمية لعام 2026.",
  },
  {
    id: "west-fn-fal-alt4",
    name: "FN FAL-ALT+F4",
    nameAr: "FN FAL-ALT+F4",
    category: "Assault Rifle",
    categoryAr: "بندقية هجومية",
    releaseDate: "2026-08-12",
    releaseName: "ALT+F4 Weapons",
    releaseNameAr: "أسلحة ALT+F4",
    imageUrl: alt4Artwork,
    imageKind: "release-artwork",
    sourceUrl: roadmapSource,
    sourceLabel: "Z8Games 2026 roadmap",
    availabilityEn: alt4AvailabilityEn,
    availabilityAr: alt4AvailabilityAr,
    descriptionEn: alt4DescriptionEn,
    descriptionAr: alt4DescriptionAr,
    verificationEn: "The individual name was captured from the official ALT+F4 roadmap detail modal. The image is the publisher's release artwork, not an individual weapon render.",
    verificationAr: "تم التقاط الاسم الفردي من نافذة تفاصيل تحديث ALT+F4 الرسمية. الصورة هي صورة الإصدار التي نشرها الناشر وليست صورة منفصلة للسلاح.",
  },
  {
    id: "west-colt-1911-alt4",
    name: "Colt 1911-ALT+F4",
    nameAr: "Colt 1911-ALT+F4",
    category: "Pistol",
    categoryAr: "مسدس",
    releaseDate: "2026-08-12",
    releaseName: "ALT+F4 Weapons",
    releaseNameAr: "أسلحة ALT+F4",
    imageUrl: alt4Artwork,
    imageKind: "release-artwork",
    sourceUrl: roadmapSource,
    sourceLabel: "Z8Games 2026 roadmap",
    availabilityEn: alt4AvailabilityEn,
    availabilityAr: alt4AvailabilityAr,
    descriptionEn: alt4DescriptionEn,
    descriptionAr: alt4DescriptionAr,
    verificationEn: "The individual name was captured from the official ALT+F4 roadmap detail modal. The image is the publisher's release artwork, not an individual weapon render.",
    verificationAr: "تم التقاط الاسم الفردي من نافذة تفاصيل تحديث ALT+F4 الرسمية. الصورة هي صورة الإصدار التي نشرها الناشر وليست صورة منفصلة للسلاح.",
  },
  {
    id: "west-bc-axe-alt4",
    name: "B.C.Axe-ALT+F4",
    nameAr: "B.C.Axe-ALT+F4",
    category: "Melee",
    categoryAr: "سلاح أبيض",
    releaseDate: "2026-08-12",
    releaseName: "ALT+F4 Weapons",
    releaseNameAr: "أسلحة ALT+F4",
    imageUrl: alt4Artwork,
    imageKind: "release-artwork",
    sourceUrl: roadmapSource,
    sourceLabel: "Z8Games 2026 roadmap",
    availabilityEn: alt4AvailabilityEn,
    availabilityAr: alt4AvailabilityAr,
    descriptionEn: alt4DescriptionEn,
    descriptionAr: alt4DescriptionAr,
    verificationEn: "The individual name was captured from the official ALT+F4 roadmap detail modal. The image is the publisher's release artwork, not an individual weapon render.",
    verificationAr: "تم التقاط الاسم الفردي من نافذة تفاصيل تحديث ALT+F4 الرسمية. الصورة هي صورة الإصدار التي نشرها الناشر وليست صورة منفصلة للسلاح.",
  },
  {
    id: "west-awm-equinox-lily-dragon",
    name: "AWM-Equinox Lily Dragon",
    nameAr: "AWM-Equinox Lily Dragon",
    category: "Sniper Rifle",
    categoryAr: "بندقية قنص",
    releaseDate: "2026-08-06",
    releaseName: "Equinox Lily Weapons",
    releaseNameAr: "أسلحة Equinox Lily",
    imageUrl: equinoxArtwork,
    imageKind: "release-artwork",
    sourceUrl: roadmapSource,
    sourceLabel: "Z8Games 2026 roadmap",
    availabilityEn: equinoxAvailabilityEn,
    availabilityAr: equinoxAvailabilityAr,
    descriptionEn: equinoxDescriptionEn,
    descriptionAr: equinoxDescriptionAr,
    verificationEn: "The individual name was captured from the official Equinox Lily roadmap detail modal. The image is the publisher's release artwork, not an individual weapon render.",
    verificationAr: "تم التقاط الاسم الفردي من نافذة تفاصيل Equinox Lily الرسمية. الصورة هي صورة الإصدار التي نشرها الناشر وليست صورة منفصلة للسلاح.",
  },
  {
    id: "west-kukri-equinox-lily-beast",
    name: "Kukri-Equinox Lily Beast",
    nameAr: "Kukri-Equinox Lily Beast",
    category: "Melee",
    categoryAr: "سلاح أبيض",
    releaseDate: "2026-08-06",
    releaseName: "Equinox Lily Weapons",
    releaseNameAr: "أسلحة Equinox Lily",
    imageUrl: equinoxArtwork,
    imageKind: "release-artwork",
    sourceUrl: roadmapSource,
    sourceLabel: "Z8Games 2026 roadmap",
    availabilityEn: equinoxAvailabilityEn,
    availabilityAr: equinoxAvailabilityAr,
    descriptionEn: equinoxDescriptionEn,
    descriptionAr: equinoxDescriptionAr,
    verificationEn: "The individual name was captured from the official Equinox Lily roadmap detail modal. The image is the publisher's release artwork, not an individual weapon render.",
    verificationAr: "تم التقاط الاسم الفردي من نافذة تفاصيل Equinox Lily الرسمية. الصورة هي صورة الإصدار التي نشرها الناشر وليست صورة منفصلة للسلاح.",
  },
  {
    id: "west-wok-equinox-lily",
    name: "Wok-Equinox Lily",
    nameAr: "Wok-Equinox Lily",
    category: "Melee",
    categoryAr: "سلاح أبيض",
    releaseDate: "2026-08-06",
    releaseName: "Equinox Lily Weapons",
    releaseNameAr: "أسلحة Equinox Lily",
    imageUrl: equinoxArtwork,
    imageKind: "release-artwork",
    sourceUrl: roadmapSource,
    sourceLabel: "Z8Games 2026 roadmap",
    availabilityEn: equinoxAvailabilityEn,
    availabilityAr: equinoxAvailabilityAr,
    descriptionEn: equinoxDescriptionEn,
    descriptionAr: equinoxDescriptionAr,
    verificationEn: "The individual name was captured from the official Equinox Lily roadmap detail modal. The image is the publisher's release artwork, not an individual weapon render.",
    verificationAr: "تم التقاط الاسم الفردي من نافذة تفاصيل Equinox Lily الرسمية. الصورة هي صورة الإصدار التي نشرها الناشر وليست صورة منفصلة للسلاح.",
  },
  {
    id: "west-qbz03-demon-release",
    name: "QBZ-03-Demon",
    nameAr: "QBZ-03-Demon",
    category: "Assault Rifle",
    categoryAr: "بندقية هجومية",
    releaseDate: "2026-08-06",
    releaseName: "QBZ-03-Demon",
    releaseNameAr: "QBZ-03-Demon",
    imageUrl: `${CATALOGUE_BASE}/C5469.png`,
    imageKind: "catalogue",
    sourceUrl: catalogueSource,
    sourceLabel: "Z8Games official weapons catalogue",
    availabilityEn: "Listed as an individual item in the current West weapons catalogue; the roadmap associates the release with the August 6 update.",
    availabilityAr: "مدرج كسجل فردي في كتالوج أسلحة الغرب الحالي؛ وتربطه خارطة الطريق بتحديث 6 أغسطس.",
    descriptionEn: "The current Z8Games catalogue exposes QBZ-03-Demon as an individual item with its own first-party CDN image. This page does not add unverified damage, recoil, or purchase claims.",
    descriptionAr: "يعرض كتالوج Z8Games الحالي سلاح QBZ-03-Demon كسجل مستقل مع صورة رسمية خاصة به من شبكة CDN. لا تضيف الصفحة أرقام ضرر أو ارتداد أو ادعاءات شراء غير موثقة.",
    verificationEn: "Individual name and image captured from the official weapons catalogue.",
    verificationAr: "تم التقاط الاسم والصورة الفردية من كتالوج الأسلحة الرسمي.",
  },
  {
    id: "west-bc-axe-stormchaser-beast",
    name: "B.C.Axe-Stormchaser Beast",
    nameAr: "B.C.Axe-Stormchaser Beast",
    category: "Melee",
    categoryAr: "سلاح أبيض",
    releaseDate: "2026-08-06",
    releaseName: "B.C.Axe-Stormchaser Beast",
    releaseNameAr: "B.C.Axe-Stormchaser Beast",
    imageUrl: `${ROADMAP_BASE}/260721_cfwe_bp_aug_main_axe_roadmapthumb.jpg`,
    imageKind: "release-artwork",
    sourceUrl: roadmapSource,
    sourceLabel: "Z8Games 2026 roadmap",
    availabilityEn: "Named as an individual August 6 roadmap release; the roadmap artwork is used until an individual catalogue render is available.",
    availabilityAr: "مذكور كسلاح مستقل ضمن إصدارات 6 أغسطس في خارطة الطريق؛ وتُستخدم صورة خارطة الطريق إلى أن تتوفر صورة منفصلة في الكتالوج.",
    descriptionEn: "A named Battle Pass weapon release recorded from the official CrossFire West roadmap. Its release context is verified, while numerical gameplay statistics remain unclaimed.",
    descriptionAr: "إصدار سلاح مستقل ضمن Battle Pass تم تسجيله من خارطة طريق CrossFire West الرسمية. سياق الإصدار موثق، بينما لا تُنسب إليه إحصاءات لعب رقمية غير منشورة.",
    verificationEn: "Release name, date, and artwork captured from the official 2026 roadmap.",
    verificationAr: "تم التقاط اسم الإصدار وتاريخه وصورته من خارطة الطريق الرسمية لعام 2026.",
  },
  {
    id: "west-at15-topographer",
    name: "AT15-Topographer",
    nameAr: "AT15-Topographer",
    category: "Machine Gun",
    categoryAr: "رشاش ثقيل",
    releaseDate: "2026-08-06",
    releaseName: "AT15-Topographer",
    releaseNameAr: "AT15-Topographer",
    imageUrl: `${ROADMAP_BASE}/260721_cfwe_bp_aug_main_at15_roadmapthumb.jpg`,
    imageKind: "release-artwork",
    sourceUrl: roadmapSource,
    sourceLabel: "Z8Games 2026 roadmap",
    availabilityEn: "Named as an individual August 6 roadmap release; the roadmap artwork is used until an individual catalogue render is available.",
    availabilityAr: "مذكور كسلاح مستقل ضمن إصدارات 6 أغسطس في خارطة الطريق؛ وتُستخدم صورة خارطة الطريق إلى أن تتوفر صورة منفصلة في الكتالوج.",
    descriptionEn: "A named Battle Pass weapon release recorded from the official CrossFire West roadmap. No unverified performance or acquisition details are added.",
    descriptionAr: "إصدار سلاح مستقل ضمن Battle Pass تم تسجيله من خارطة طريق CrossFire West الرسمية. لا تتم إضافة تفاصيل غير موثقة عن الأداء أو طريقة الحصول.",
    verificationEn: "Release name, date, and artwork captured from the official 2026 roadmap.",
    verificationAr: "تم التقاط اسم الإصدار وتاريخه وصورته من خارطة الطريق الرسمية لعام 2026.",
  },
  {
    id: "west-mg3-ignite",
    name: "MG3-Ignite",
    nameAr: "MG3-Ignite",
    category: "Machine Gun",
    categoryAr: "رشاش ثقيل",
    releaseDate: "2026-08-06",
    releaseName: "MG3-Ignite",
    releaseNameAr: "MG3-Ignite",
    imageUrl: `${ROADMAP_BASE}/260728_cfwe_mg3ignite_roadmapthumb.jpg`,
    imageKind: "release-artwork",
    sourceUrl: roadmapSource,
    sourceLabel: "Z8Games 2026 roadmap",
    availabilityEn: "Named as an individual August 6 roadmap release; the roadmap artwork is used until an individual catalogue render is available.",
    availabilityAr: "مذكور كسلاح مستقل ضمن إصدارات 6 أغسطس في خارطة الطريق؛ وتُستخدم صورة خارطة الطريق إلى أن تتوفر صورة منفصلة في الكتالوج.",
    descriptionEn: "A named weapon release recorded from the official CrossFire West roadmap. The archive keeps the publisher's name and release artwork without inventing numerical statistics.",
    descriptionAr: "إصدار سلاح مستقل تم تسجيله من خارطة طريق CrossFire West الرسمية. يحتفظ الأرشيف باسم الناشر وصورة الإصدار دون اختلاق إحصاءات رقمية.",
    verificationEn: "Release name, date, and artwork captured from the official 2026 roadmap.",
    verificationAr: "تم التقاط اسم الإصدار وتاريخه وصورته من خارطة الطريق الرسمية لعام 2026.",
  },
  {
    id: "west-mosin-nagant-vietnam-heritage",
    name: "Mosin Nagant-Vietnam Heritage",
    nameAr: "Mosin Nagant-Vietnam Heritage",
    category: "Sniper Rifle",
    categoryAr: "بندقية قنص",
    releaseDate: "2026-08-06",
    releaseName: "Vietnam Heritage Weapons",
    releaseNameAr: "أسلحة Vietnam Heritage",
    imageUrl: "https://z8games.akamaized.net/cfna/web/inventory/weapons/300_169/W9520.png",
    imageKind: "catalogue",
    sourceUrl: inventorySource,
    sourceLabel: "Z8Games public inventory record",
    availabilityEn: "Listed as one of the three individual Vietnam Heritage collection weapons in the public Z8Games inventory record.",
    availabilityAr: "مدرج كواحد من أسلحة مجموعة Vietnam Heritage الثلاثة في سجل مخزون Z8Games العام.",
    descriptionEn: "The public inventory presents Mosin Nagant-Vietnam Heritage with an individual first-party CDN image. The release group and date are cross-checked against the August 6 roadmap entry.",
    descriptionAr: "يعرض المخزون العام Mosin Nagant-Vietnam Heritage بصورة CDN رسمية مستقلة. تمت مطابقة مجموعة الإصدار وتاريخها مع إدخال 6 أغسطس في خارطة الطريق.",
    verificationEn: "Name and image verified on the public Z8Games inventory page; the collection count is cross-checked on the official collections page.",
    verificationAr: "تم التحقق من الاسم والصورة في صفحة مخزون Z8Games العامة، مع مطابقة عدد المجموعة في صفحة التجميع الرسمية.",
  },
  {
    id: "west-ak47-scope-vietnam-heritage",
    name: "AK-47-Scope-Vietnam Heritage",
    nameAr: "AK-47-Scope-Vietnam Heritage",
    category: "Assault Rifle",
    categoryAr: "بندقية هجومية",
    releaseDate: "2026-08-06",
    releaseName: "Vietnam Heritage Weapons",
    releaseNameAr: "أسلحة Vietnam Heritage",
    imageUrl: "https://z8games.akamaized.net/cfna/web/inventory/weapons/300_169/W9205.png",
    imageKind: "catalogue",
    sourceUrl: inventorySource,
    sourceLabel: "Z8Games public inventory record",
    availabilityEn: "Listed as one of the three individual Vietnam Heritage collection weapons in the public Z8Games inventory record.",
    availabilityAr: "مدرج كواحد من أسلحة مجموعة Vietnam Heritage الثلاثة في سجل مخزون Z8Games العام.",
    descriptionEn: "AK-47-Scope-Vietnam Heritage is represented by its own first-party CDN image in the public inventory. The archive does not infer scope behavior or numerical performance.",
    descriptionAr: "يظهر AK-47-Scope-Vietnam Heritage بصورة CDN رسمية مستقلة في المخزون العام. لا يستنتج الأرشيف سلوك المنظار أو أرقام الأداء.",
    verificationEn: "Name and image verified on the public Z8Games inventory page; the collection count is cross-checked on the official collections page.",
    verificationAr: "تم التحقق من الاسم والصورة في صفحة مخزون Z8Games العامة، مع مطابقة عدد المجموعة في صفحة التجميع الرسمية.",
  },
  {
    id: "west-hk417-vietnam-heritage-beast",
    name: "HK417-Vietnam Heritage Beast",
    nameAr: "HK417-Vietnam Heritage Beast",
    category: "Assault Rifle",
    categoryAr: "بندقية هجومية",
    releaseDate: "2026-08-06",
    releaseName: "Vietnam Heritage Weapons",
    releaseNameAr: "أسلحة Vietnam Heritage",
    imageUrl: "https://z8games.akamaized.net/cfna/web/inventory/weapons/300_169/W9523.png",
    imageKind: "catalogue",
    sourceUrl: inventorySource,
    sourceLabel: "Z8Games public inventory record",
    availabilityEn: "Listed as one of the three individual Vietnam Heritage collection weapons in the public Z8Games inventory record.",
    availabilityAr: "مدرج كواحد من أسلحة مجموعة Vietnam Heritage الثلاثة في سجل مخزون Z8Games العام.",
    descriptionEn: "HK417-Vietnam Heritage Beast has an individual first-party CDN image in the public inventory. The archive records the publisher’s exact name without adding unsupported statistics.",
    descriptionAr: "يمتلك HK417-Vietnam Heritage Beast صورة CDN رسمية مستقلة في المخزون العام. يسجل الأرشيف اسم الناشر بدقة دون إضافة إحصاءات غير مدعومة.",
    verificationEn: "Name and image verified on the public Z8Games inventory page; the collection count is cross-checked on the official collections page.",
    verificationAr: "تم التحقق من الاسم والصورة في صفحة مخزون Z8Games العامة، مع مطابقة عدد المجموعة في صفحة التجميع الرسمية.",
  },
  {
    id: "west-light-stick-ship",
    name: "Light Stick-Ship",
    nameAr: "Light Stick-Ship",
    category: "Melee",
    categoryAr: "سلاح أبيض",
    releaseDate: "2026-08-06",
    releaseName: "Ship Weapons",
    releaseNameAr: "أسلحة Ship",
    imageUrl: "https://z8games.akamaized.net/cfna/web/inventory/weapons/300_169/C4041.png",
    imageKind: "catalogue",
    sourceUrl: inventorySource,
    sourceLabel: "Z8Games public inventory record",
    availabilityEn: "One individually named Ship collection item confirmed in the public Z8Games inventory; the official collections page lists four total Ship items, so the remaining three are intentionally not guessed.",
    availabilityAr: "تم تأكيد عنصر واحد باسم مستقل من مجموعة Ship في مخزون Z8Games العام؛ وتعرض صفحة التجميع الرسمية أربعة عناصر، لذلك لم يتم تخمين العناصر الثلاثة المتبقية.",
    descriptionEn: "Light Stick-Ship is shown with an individual first-party CDN image and is presented as a standalone weapon record. The archive keeps the remaining Ship collection gap explicit rather than filling it with unverified names.",
    descriptionAr: "يظهر Light Stick-Ship بصورة CDN رسمية مستقلة ويُعرض كسجل سلاح منفصل. يوضح الأرشيف أن بقية مجموعة Ship ما زالت غير مكتملة بدل ملئها بأسماء غير موثقة.",
    verificationEn: "Name and image verified on the public Z8Games inventory page; the four-item Ship collection count is cross-checked on the official collections page.",
    verificationAr: "تم التحقق من الاسم والصورة في صفحة مخزون Z8Games العامة، مع مطابقة عدد عناصر مجموعة Ship الأربعة في صفحة التجميع الرسمية.",
  },
];

export const WEST_RECENT_WEAPONS_LAST_VERIFIED = "2026-08-17";
