import { createContext, useContext, useEffect, useState } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    about: "About",
    contact: "Contact",
    categories: "Categories",
    all: "All",
    news: "News",
    reviews: "Reviews",
    tutorials: "Tutorials",
    videos: "Videos",
    events: "Events",
    search: "Search articles...",
    readMore: "Read More",
    recentPosts: "Recent Posts",
    popularTags: "Popular Tags",
    mostViewed: "Most Viewed",
    bimoraPicks: "Bimora's Picks",
    readingTime: "min read",
    views: "views",
    latest: "Latest",
    popular: "Popular",
    featured: "Featured",
    relatedArticles: "Related Articles",
    comments: "Comments",
    addComment: "Add a comment",
    submit: "Submit",
    admin: "Admin Dashboard",
    logout: "Logout",
    login: "Login",
    signUp: "Sign Up",
    copyright: "© 2025 Bimora Gaming — All Rights Reserved",
    loading: "Loading...",
    newsNotFound: "News Not Found",
    backToNews: "Back to News",
    readMoreNews: "Read More News",
    newsAndUpdates: "News & Updates",
    translationNote: "Translation Note:",
    translationNoteText: "This article will be automatically translated using AI translation API when implemented.",
    mercenaries: "Mercenaries",
    mercenariesSubtitle: "Choose your warrior. Master your destiny.",
    graveGames: "GRAVE GAMES",
    graveGamesSubtitle: "The Spider's Web Awaits",
    eventDescription: "Enter the Spider's Web this Halloween season! Complete thrilling challenges, earn exclusive rewards, and prove your skills in this limited-time event.",
    eventDetails: "Navigate through the treacherous web of challenges designed to test even the most experienced mercenaries. Each completed challenge brings you closer to unlocking rare weapons, character skins, and special Halloween-themed items.",
    eventFeatures: "Event Features",
    eventFeature1: "Complete daily and weekly challenges",
    eventFeature2: "Earn exclusive Halloween-themed rewards",
    eventFeature3: "Unlock special character skins and weapon camos",
    eventFeature4: "Track your progress through the event portal",
    eventFeature5: "Compete with other mercenaries on the leaderboard",
    limitedTimeOnly: "Limited Time Only",
    limitedTimeText: "This event runs from October 1st through October 31st. Don't miss your chance to collect these exclusive Halloween items before the web disappears!",
    aboutBimora: "About Bimora Gaming",
    aboutWelcome: "Welcome to Bimora Gaming, your premier source for CrossFire news, character guides, weapon reviews, and gaming updates.",
    ourMission: "Our Mission",
    missionText: "We're dedicated to providing comprehensive CrossFire gaming content that helps players stay updated with the latest news, master new characters, and improve their gameplay. From beginner guides to advanced strategies, we cover it all.",
    whatWeCover: "What We Cover",
    coverItem1: "CrossFire game news and updates",
    coverItem2: "Character guides and mercenary profiles",
    coverItem3: "Weapon reviews and gameplay tips",
    coverItem4: "Community events and tournaments",
    coverItem5: "Game modes and strategy guides",
    joinCommunity: "Join Our Community",
    communityText: "Connect with fellow CrossFire players, share your gaming experiences, and stay updated with the latest game updates. Follow us on social media and subscribe to our newsletter for regular updates.",
    contactUs: "Contact Us",
    contactSubtitle: "Have a question or suggestion? We'd love to hear from you.",
    email: "Email",
    chat: "Chat",
    liveChatSupport: "Live chat support",
    notFound: "404 Page Not Found",
    notFoundText: "This page doesn't exist or may have been removed.",
    backToHome: "Go back home",
    eventInformation: "Event Information",
    theSpidersWeb: "The Spider's Web",
    eventDates: "October 1 - 31, 2025",
    loginToCheckProgress: "Login to Check Your Progress",
    social: "Social",
    followUsOnline: "Follow us online",
    sendUsMessage: "Send us a message",
    name: "Name",
    yourName: "Your name",
    yourEmail: "your@email.com",
    message: "Message",
    tellUsWhatsOnYourMind: "Tell us what's on your mind...",
    eventNotFound: "Event Not Found",
    back: "Back",
    upcoming: "Upcoming",
    trending: "Trending",
    showOriginal: "Show Original",
    showTranslation: "Show Translation",
    viewingTranslation: "You are viewing the translated version",
    translationAvailable: "Translation available - click the button above to switch",
    explore: "Explore",
    modes: "Modes",
    maps: "Maps",
    ranks: "Ranks",
    weapons: "Weapons",
    posts: "Posts",
    blog: "Blog",
    support: "Support",
    pricing: "Pricing",
    sellers: "Sellers",
    supportTickets: "Support Tickets",
    createTicket: "Create Ticket",
    download: "Download",
    noArticlesFound: "No articles found",
    faq: "FAQ",
    faqFull: "Frequently Asked Questions",
    faqSubtitle: "Find answers to the most common questions about CrossFire.",
    faqSearch: "Search questions...",
    faqNoResults: "No results found. Try different keywords.",
    faqStillNeedHelp: "Still can't find your answer?",
    faqContactPrompt: "Our support team is here to help. Submit a ticket and we'll get back to you.",
    faqSubmitTicket: "Submit a Support Ticket",
    faqAllTopics: "All Topics",
    faqCategories: "FAQ Categories",
    faqManage: "Manage FAQ",
    faqAddCategory: "Add Category",
    faqEditCategory: "Edit Category",
    faqDeleteCategory: "Delete Category",
    faqAddQuestion: "Add Question",
    faqEditQuestion: "Edit Question",
    faqDeleteQuestion: "Delete Question",
    faqCategoryName: "Category Name",
    faqCategoryNameAr: "Category Name (Arabic)",
    faqQuestion: "Question",
    faqQuestionAr: "Question (Arabic)",
    faqAnswer: "Answer",
    faqAnswerAr: "Answer (Arabic)",

    tableOfContents: "Table of Contents",
    quickTips: "Quick Tips",
    backToTop: "Back to top",
    countdown: "Countdown",
    eventStatus: "Event status",
    published: "Published",
    currentLanguage: "Language",
    headingsPlaceholder: "Headings will appear here when the event content includes sections.",
    eventDatePending: "Event date will be updated soon",
    eventLiveOrEnded: "Event is live or already ended",
    navNews: "NEWS",
    navGame: "GAME",
    navShop: "SHOP",
    navCommunity: "COMMUNITY",
    navSupport: "SUPPORT",
    navUpdates: "Updates",
    navGameOverview: "Game Overview",
    navModes: "Modes",
    navMaps: "Maps",
    navWeapons: "Weapons",
    navMercenaries: "Mercenaries",
    navRankings: "Rankings",
    navDownload: "Download",
    navSellers: "Sellers",
    navBrowseItems: "Browse Items",
    navForum: "Forum",
    navReviews: "Reviews",
    navContact: "Contact",
    navFAQ: "FAQ",
    navSubmitTicket: "Submit Ticket",
    navMyTickets: "My Tickets",
    navProfile: "Profile",
    navLogout: "Logout",
    navEvents: "Events",
    navVideos: "Videos",
    searchPlaceholder: "Search...",
    downloadNow: "Download Now",
    downloadCrossFire: "Download CrossFire",
    latestAnnouncements: "Latest announcements",
    officialInstaller: "Official installer",
    officialInstallerDesc: "Download the latest CrossFire installer from the official Z8Games page to avoid broken or outdated mirrors.",
    checkUpdatesFirst: "Check updates first",
    checkUpdatesDesc: "Review current announcements and patch notes before reinstalling so you know whether maintenance or launcher updates are active.",
    useEnoughStorage: "Use enough storage",
    useEnoughStorageDesc: "Keep extra free disk space available for updates, anticheat files, and temporary installer extraction.",
    systemRequirements: "System Requirements",
    readyToJoin: "Ready to join the battle?",
    readyToJoinDesc: "Download CrossFire now and experience intense multiplayer action. Check the system requirements above to ensure your PC meets the minimum specifications.",
    minimum: "Minimum:",
    recommended: "Recommended:",
    leaveComment: "Leave a Comment",
    yourNameRequired: "Your name (Required)",
    emailOptional: "Email (Optional)",
    writeComment: "Write your comment...",
    replyTo: "Reply to",
    submitReply: "Submit Reply",
    cancel: "Cancel",
    deleteComment: "Delete",
    reply: "Reply",
    beFirstToComment: "Be the first to comment!",
    commentPosted: "Comment posted!",
    failedToPost: "Failed to post",

    // Header
    navTutorials: "Tutorials",

    // Footer
    footerStayInformed: "Stay Informed",
    footerNewsEventsTitle: "CrossFire News & Events",
    footerNewsletterSubtitle: "Weekly digest of updates, tournaments and guides.",
    footerEmailPlaceholder: "Your email address",
    footerSubscribe: "Subscribe",
    footerSubscribed: "Subscribed!",
    footerBackToTop: "BACK TO TOP",
    footerNewsSection: "NEWS",
    footerGameSection: "GAME",
    footerCommunitySection: "COMMUNITY",
    footerShopSection: "SHOP",
    footerSupportSection: "SUPPORT",
    footerFollowSection: "FOLLOW CROSSFIRE",
    footerLatestNews: "Latest News",
    footerUpdates: "Updates",
    footerGameOverview: "Game Overview",
    footerGameModes: "Game Modes",
    footerForumPosts: "Forum / Posts",
    footerTutorials: "Tutorials",
    footerContactUs: "Contact Us",
    footerSellersMarket: "Sellers Market",
    footerCommunityReviews: "Community Reviews",
    footerSubmitTicket: "Submit Ticket",
    footerMyTickets: "My Tickets",
    footerJoinCommunity: "JOIN COMMUNITY",
    footerWhatsappChannel: "WhatsApp Channel",
    footerPlayNow: "PLAY NOW",
    footerDownloadCF: "Download CrossFire",
    footerPrivacy: "Privacy",
    footerTerms: "Terms",

    // Support page
    supportCenter: "Support Center",
    supportSubmitTitle: "Submit a Ticket",
    supportNeedHelp: "Need help? Fill out the form below and our team will get back to you.",
    supportJoinWhatsapp: "Join our WhatsApp channel for updates and quick community support.",
    supportOpenChannel: "Open Channel",
    supportResponseTime: "Response Time",
    supportEmailUpdates: "Email Updates",
    supportTrackStatus: "Track Status",
    supportAutoNotify: "Auto-notify",
    supportMyTickets: "My Tickets",
    supportTicketSuccess: "Ticket submitted successfully! Check your email for updates.",
    supportTicketFormTitle: "Support Ticket Form",
    supportAllRequired: "All fields are required unless marked optional.",
    supportYourName: "Your Name",
    supportEmailAddress: "Email Address",
    supportCategory: "Category",
    supportSelectCategory: "Select a category",
    supportCategoryTech: "Technical Issue",
    supportCategoryAccount: "Account Support",
    supportCategoryBilling: "Billing Question",
    supportCategoryFeature: "Feature Request",
    supportCategoryBug: "Bug Report",
    supportCategoryOther: "Other",
    supportPriority: "Priority",
    supportSelectPriority: "Select priority",
    supportLow: "Low",
    supportNormal: "Normal",
    supportHigh: "High",
    supportSubject: "Subject",
    supportSubjectPlaceholder: "Brief description of your issue",
    supportDescription: "Description",
    supportDescriptionPlaceholder: "Please provide detailed information about your issue...",
    supportAttachment: "Attachment (optional)",
    supportUploadImage: "Upload Screenshot or Image",
    supportImageUploaded: "✓ Image uploaded — will be included with your ticket",
    supportSubmitting: "Submitting…",
    supportSubmitBtn: "Submit Ticket",
    supportTicketToast: "Ticket Submitted",
    supportTicketToastDesc: "Your support ticket has been submitted. We'll get back to you soon!",
    supportErrorToast: "Error",
    supportBreadcrumbHome: "Home",

    // Contact page
    contactGetInTouch: "Get In Touch",
    contactSubtitleFull: "Have a question, suggestion, or want to contribute? We'd love to hear from you.",
    contactEmailTitle: "Email",
    contactEmailDesc: "Response within 24–48 hours",
    contactTicketTitle: "Support Ticket",
    contactTicketValue: "Official support system",
    contactTicketDesc: "Submit and track your request",
    contactWhatsappValue: "Join WhatsApp updates",
    contactWhatsappDesc: "News, alerts, and community support",
    contactMessageSent: "Message Sent!",
    contactMessageSentDesc: "We'll get back to you within 24–48 hours.",
    contactFailedSend: "Failed to send. Please try again or email us directly.",
    contactSending: "Sending…",
    contactFollowUs: "Follow Us",
    contactNeedSupport: "Need Support?",
    contactNeedSupportDesc: "For account issues, bugs, or ZP seller disputes, submit an official ticket.",
    contactSubmitTicketBtn: "Submit Ticket",

    // Login page
    loginTitle: "Sign In",
    loginWelcome: "Welcome back to CrossFire Wiki",
    loginCFResource: "CF Resource",
    loginTagline: "Weapons, mercenaries, ranks, maps, events — everything you need to dominate.",
    loginEmailLabel: "Email / Username / Phone",
    loginEmailPlaceholder: "Enter your identifier",
    loginPasswordLabel: "Password",
    loginSigningIn: "Signing In...",
    loginSignIn: "Sign In",
    loginNoAccount: "Don't have an account?",
    loginCreateOne: "Create one",
    loginRankCalc: "Rank Progression Calculator",
    loginArsenalDB: "Full Arsenal Database",
    loginLiveEvents: "Live Events & Updates",
  },
  ar: {
    home: "الرئيسية",
    about: "من نحن",
    contact: "اتصل بنا",
    categories: "التصنيفات",
    all: "الكل",
    news: "أخبار",
    reviews: "مراجعات",
    tutorials: "دروس",
    videos: "فيديوهات",
    events: "فعاليات",
    search: "ابحث عن المقالات...",
    readMore: "اقرأ المزيد",
    recentPosts: "آخر المقالات",
    popularTags: "الوسوم الشائعة",
    mostViewed: "الأكثر مشاهدة",
    bimoraPicks: "اختيارات بيوميرا",
    readingTime: "دقيقة قراءة",
    views: "مشاهدة",
    latest: "الأحدث",
    popular: "الأكثر شعبية",
    featured: "مميز",
    relatedArticles: "مقالات ذات صلة",
    comments: "التعليقات",
    addComment: "أضف تعليقاً",
    submit: "إرسال",
    admin: "لوحة الإدارة",
    logout: "تسجيل الخروج",
    login: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    copyright: "© 2025 Bimora Gaming — جميع الحقوق محفوظة",
    loading: "جاري التحميل...",
    newsNotFound: "الخبر غير موجود",
    backToNews: "العودة للأخبار",
    readMoreNews: "اقرأ المزيد من الأخبار",
    newsAndUpdates: "والتحديثات",
    translationNote: "ملاحظة الترجمة:",
    translationNoteText: "سيتم ترجمة هذا المقال تلقائياً باستخدام واجهة برمجة التطبيقات للترجمة الآلية عند التفعيل.",
    mercenaries: "الشخصيات",
    mercenariesSubtitle: "اختر محاربك. أتقن مصيرك.",
    graveGames: "ألعاب القبور",
    graveGamesSubtitle: "شبكة العنكبوت في الانتظار",
    eventDescription: "ادخل شبكة العنكبوت في موسم الهالوين هذا! أكمل التحديات المثيرة، واكسب مكافآت حصرية، وأثبت مهاراتك في هذا الحدث محدود المدة.",
    eventDetails: "تنقل عبر شبكة التحديات الخطيرة المصممة لاختبار حتى أكثر المرتزقة خبرة. كل تحدٍ مكتمل يقربك من فتح أسلحة نادرة، وأزياء شخصيات، وعناصر خاصة بالهالوين.",
    eventFeatures: "ميزات الحدث",
    eventFeature1: "أكمل التحديات اليومية والأسبوعية",
    eventFeature2: "اكسب مكافآت حصرية بطابع الهالوين",
    eventFeature3: "افتح أزياء شخصيات خاصة وتمويه أسلحة",
    eventFeature4: "تتبع تقدمك عبر بوابة الحدث",
    eventFeature5: "تنافس مع مرتزقة آخرين على لوحة المتصدرين",
    limitedTimeOnly: "لفترة محدودة فقط",
    limitedTimeText: "يستمر هذا الحدث من 1 أكتوبر حتى 31 أكتوبر. لا تفوت فرصتك لجمع هذه العناصر الحصرية للهالوين قبل اختفاء الشبكة!",
    aboutBimora: "عن Bimora Gaming",
    aboutWelcome: "مرحباً بك في Bimora Gaming، مصدرك الأول لأخبار CrossFire، وأدلة الشخصيات، ومراجعات الأسلحة، وتحديثات الألعاب.",
    ourMission: "مهمتنا",
    missionText: "نحن ملتزمون بتوفير محتوى شامل عن ألعاب CrossFire يساعد اللاعبين على البقاء على اطلاع بأحدث الأخبار، وإتقان الشخصيات الجديدة، وتحسين أسلوب اللعب. من أدلة المبتدئين إلى الاستراتيجيات المتقدمة، نغطي كل شيء.",
    whatWeCover: "ما نغطيه",
    coverItem1: "أخبار وتحديثات لعبة CrossFire",
    coverItem2: "أدلة الشخصيات وملفات المرتزقة",
    coverItem3: "مراجعات الأسلحة ونصائح اللعب",
    coverItem4: "الفعاليات المجتمعية والبطولات",
    coverItem5: "أوضاع اللعب وأدلة الاستراتيجيات",
    joinCommunity: "انضم إلى مجتمعنا",
    communityText: "تواصل مع زملائك لاعبي CrossFire، وشارك تجاربك في الألعاب، وابق على اطلاع بأحدث تحديثات اللعبة. تابعنا على وسائل التواصل الاجتماعي واشترك في نشرتنا الإخبارية للحصول على تحديثات منتظمة.",
    contactUs: "اتصل بنا",
    contactSubtitle: "هل لديك سؤال أو اقتراح؟ نود أن نسمع منك.",
    email: "البريد الإلكتروني",
    chat: "الدردشة",
    liveChatSupport: "دعم الدردشة المباشرة",
    notFound: "الصفحة غير موجودة 404",
    notFoundText: "هذه الصفحة غير موجودة أو ربما تمت إزالتها.",
    backToHome: "العودة للصفحة الرئيسية",
    eventInformation: "معلومات الحدث",
    theSpidersWeb: "شبكة العنكبوت",
    eventDates: "1 - 31 أكتوبر 2025",
    loginToCheckProgress: "تسجيل الدخول لمتابعة تقدمك",
    social: "التواصل الاجتماعي",
    followUsOnline: "تابعنا عبر الإنترنت",
    sendUsMessage: "أرسل لنا رسالة",
    name: "الاسم",
    yourName: "اسمك",
    yourEmail: "بريدك@الإلكتروني.com",
    message: "الرسالة",
    tellUsWhatsOnYourMind: "أخبرنا بما يدور في ذهنك...",
    eventNotFound: "الحدث غير موجود",
    back: "رجوع",
    upcoming: "قادم",
    trending: "رائج",
    showOriginal: "عرض النص الأصلي",
    showTranslation: "عرض الترجمة",
    viewingTranslation: "أنت تشاهد النسخة المترجمة",
    translationAvailable: "الترجمة متوفرة - انقر الزر أعلاه للتبديل",
    explore: "استكشف",
    modes: "الأوضاع",
    maps: "الخرائط",
    ranks: "الرتب",
    weapons: "الأسلحة",
    posts: "المقالات",
    blog: "المدونة",
    support: "الدعم",
    pricing: "التسعير",
    sellers: "البائعون",
    supportTickets: "تذاكر الدعم",
    createTicket: "إنشاء تذكرة",
    download: "تحميل",
    noArticlesFound: "لم يتم العثور على مقالات",
    faq: "الأسئلة الشائعة",
    faqFull: "الأسئلة الشائعة",
    faqSubtitle: "لاقي إجابات على أكتر الأسئلة شيوعًا عن CrossFire.",
    faqSearch: "ابحث في الأسئلة...",
    faqNoResults: "مش لاقي نتايج. جرب كلمات تانية.",
    faqStillNeedHelp: "مش لاقي إجابتك؟",
    faqContactPrompt: "فريق الدعم بتاعنا موجود يساعدك. ابعتلنا تذكرة وهنرد عليك بسرعة.",
    faqSubmitTicket: "ابعت تذكرة ساببورت",
    faqAllTopics: "كل المواضيع",
    faqCategories: "تصنيفات الأسئلة",
    faqManage: "إدارة الأسئلة الشائعة",
    faqAddCategory: "إضافة تصنيف",
    faqEditCategory: "تعديل التصنيف",
    faqDeleteCategory: "حذف التصنيف",
    faqAddQuestion: "إضافة سؤال",
    faqEditQuestion: "تعديل السؤال",
    faqDeleteQuestion: "حذف السؤال",
    faqCategoryName: "اسم التصنيف",
    faqCategoryNameAr: "اسم التصنيف (عربي)",
    faqQuestion: "السؤال",
    faqQuestionAr: "السؤال (عربي)",
    faqAnswer: "الإجابة",
    faqAnswerAr: "الإجابة (عربي)",

    tableOfContents: "محتويات الصفحة",
    quickTips: "نصائح سريعة",
    backToTop: "العودة للأعلى",
    countdown: "العد التنازلي",
    eventStatus: "حالة الحدث",
    published: "تاريخ النشر",
    currentLanguage: "اللغة",
    headingsPlaceholder: "ستظهر العناوين هنا عندما يحتوي محتوى الحدث على أقسام واضحة.",
    eventDatePending: "سيتم تحديث الموعد قريباً",
    eventLiveOrEnded: "انتهى الحدث أو بدأ بالفعل",
    navNews: "الأخبار",
    navGame: "اللعبة",
    navShop: "المتجر",
    navCommunity: "المجتمع",
    navSupport: "الدعم",
    navUpdates: "التحديثات",
    navGameOverview: "نظرة عامة",
    navModes: "الأوضاع",
    navMaps: "الخرائط",
    navWeapons: "الأسلحة",
    navMercenaries: "الشخصيات",
    navRankings: "الرتب",
    navDownload: "تحميل",
    navSellers: "البائعون",
    navBrowseItems: "تصفح العناصر",
    navForum: "المنتدى",
    navReviews: "المراجعات",
    navContact: "اتصل بنا",
    navFAQ: "الأسئلة الشائعة",
    navSubmitTicket: "رفع تذكرة",
    navMyTickets: "تذاكري",
    navProfile: "الملف الشخصي",
    navLogout: "تسجيل الخروج",
    navEvents: "الفعاليات",
    navVideos: "فيديوهات",
    searchPlaceholder: "ابحث...",
    downloadNow: "حمّل الآن",
    downloadCrossFire: "حمّل CrossFire",
    latestAnnouncements: "آخر الإعلانات",
    officialInstaller: "النسخة الرسمية",
    officialInstallerDesc: "حمّل أحدث نسخة من CrossFire من صفحة Z8Games الرسمية لتجنب النسخ المعطوبة أو القديمة.",
    checkUpdatesFirst: "تحقق من التحديثات أولاً",
    checkUpdatesDesc: "اطلع على الإعلانات وملاحظات التحديثات قبل إعادة التثبيت حتى تعرف إذا كان هناك صيانة أو تحديثات للمشغل.",
    useEnoughStorage: "تأكد من مساحة التخزين",
    useEnoughStorageDesc: "احتفظ بمساحة قرص حرة كافية للتحديثات وملفات مكافحة الغش واستخراج المثبت المؤقت.",
    systemRequirements: "متطلبات التشغيل",
    readyToJoin: "مستعد للانضمام للمعركة؟",
    readyToJoinDesc: "حمّل CrossFire الآن وعش تجربة لعب جماعي مكثف. تحقق من متطلبات التشغيل أعلاه للتأكد أن جهازك يلبي المواصفات الدنيا.",
    minimum: "الحد الأدنى:",
    recommended: "موصى به:",
    leaveComment: "اترك تعليقاً",
    yourNameRequired: "اسمك (مطلوب)",
    emailOptional: "البريد الإلكتروني (اختياري)",
    writeComment: "اكتب تعليقك...",
    replyTo: "رد على",
    submitReply: "إرسال الرد",
    cancel: "إلغاء",
    deleteComment: "حذف",
    reply: "رد",
    beFirstToComment: "كن أول من يعلق!",
    commentPosted: "تم نشر التعليق!",
    failedToPost: "فشل في النشر",

    // Header
    navTutorials: "الدروس",

    // Footer
    footerStayInformed: "ابقَ على اطلاع",
    footerNewsEventsTitle: "أخبار وفعاليات CrossFire",
    footerNewsletterSubtitle: "ملخص أسبوعي للتحديثات والبطولات والأدلة.",
    footerEmailPlaceholder: "بريدك الإلكتروني",
    footerSubscribe: "اشترك",
    footerSubscribed: "تم الاشتراك!",
    footerBackToTop: "العودة للأعلى",
    footerNewsSection: "الأخبار",
    footerGameSection: "اللعبة",
    footerCommunitySection: "المجتمع",
    footerShopSection: "المتجر",
    footerSupportSection: "الدعم",
    footerFollowSection: "تابع CrossFire",
    footerLatestNews: "آخر الأخبار",
    footerUpdates: "التحديثات",
    footerGameOverview: "نظرة عامة على اللعبة",
    footerGameModes: "أوضاع اللعب",
    footerForumPosts: "المنتدى والمقالات",
    footerTutorials: "الدروس",
    footerContactUs: "اتصل بنا",
    footerSellersMarket: "سوق البائعين",
    footerCommunityReviews: "تقييمات المجتمع",
    footerSubmitTicket: "رفع تذكرة",
    footerMyTickets: "تذاكري",
    footerJoinCommunity: "انضم للمجتمع",
    footerWhatsappChannel: "قناة واتساب",
    footerPlayNow: "العب الآن",
    footerDownloadCF: "حمّل CrossFire",
    footerPrivacy: "الخصوصية",
    footerTerms: "الشروط",

    // Support page
    supportCenter: "مركز الدعم",
    supportSubmitTitle: "ارفع تذكرة",
    supportNeedHelp: "محتاج مساعدة؟ املأ الفورم وفريقنا هيرد عليك.",
    supportJoinWhatsapp: "انضم لقناة واتساب بتاعتنا للتحديثات والدعم السريع.",
    supportOpenChannel: "افتح القناة",
    supportResponseTime: "وقت الرد",
    supportEmailUpdates: "تحديثات البريد",
    supportTrackStatus: "تتبع الحالة",
    supportAutoNotify: "تلقائي",
    supportMyTickets: "تذاكري",
    supportTicketSuccess: "تم رفع التذكرة بنجاح! تحقق من بريدك للتحديثات.",
    supportTicketFormTitle: "فورم تذكرة الدعم",
    supportAllRequired: "كل الحقول مطلوبة إلا اللي مكتوب عليها اختياري.",
    supportYourName: "اسمك",
    supportEmailAddress: "البريد الإلكتروني",
    supportCategory: "التصنيف",
    supportSelectCategory: "اختار تصنيف",
    supportCategoryTech: "مشكلة تقنية",
    supportCategoryAccount: "دعم الحساب",
    supportCategoryBilling: "سؤال عن الفواتير",
    supportCategoryFeature: "طلب ميزة",
    supportCategoryBug: "بلاغ باج",
    supportCategoryOther: "أخرى",
    supportPriority: "الأولوية",
    supportSelectPriority: "اختار الأولوية",
    supportLow: "منخفض",
    supportNormal: "عادي",
    supportHigh: "عالي",
    supportSubject: "الموضوع",
    supportSubjectPlaceholder: "وصف مختصر للمشكلة",
    supportDescription: "التفاصيل",
    supportDescriptionPlaceholder: "اكتب تفاصيل المشكلة بالكامل...",
    supportAttachment: "مرفق (اختياري)",
    supportUploadImage: "ارفع سكرين شوت أو صورة",
    supportImageUploaded: "✓ تم رفع الصورة — هتتحط مع التذكرة",
    supportSubmitting: "جاري الإرسال...",
    supportSubmitBtn: "ارفع التذكرة",
    supportTicketToast: "تم رفع التذكرة",
    supportTicketToastDesc: "تم إرسال تذكرة الدعم. هنرد عليك قريباً!",
    supportErrorToast: "خطأ",
    supportBreadcrumbHome: "الرئيسية",

    // Contact page
    contactGetInTouch: "تواصل معنا",
    contactSubtitleFull: "عندك سؤال أو اقتراح أو عايز تشارك؟ يسعدنا نسمع منك.",
    contactEmailTitle: "البريد الإلكتروني",
    contactEmailDesc: "رد خلال 24–48 ساعة",
    contactTicketTitle: "تذكرة دعم",
    contactTicketValue: "نظام الدعم الرسمي",
    contactTicketDesc: "ارفع وتابع طلبك",
    contactWhatsappValue: "انضم لتحديثات واتساب",
    contactWhatsappDesc: "أخبار وتنبيهات ودعم المجتمع",
    contactMessageSent: "تم إرسال الرسالة!",
    contactMessageSentDesc: "هنرد عليك خلال 24–48 ساعة.",
    contactFailedSend: "فشل الإرسال. جرب تاني أو راسلنا على البريد مباشرة.",
    contactSending: "جاري الإرسال...",
    contactFollowUs: "تابعنا",
    contactNeedSupport: "محتاج دعم؟",
    contactNeedSupportDesc: "لمشاكل الحساب أو الباج أو نزاعات البائعين، ارفع تذكرة رسمية.",
    contactSubmitTicketBtn: "ارفع تذكرة",

    // Login page
    loginTitle: "تسجيل الدخول",
    loginWelcome: "أهلاً بعودتك لـ CrossFire Wiki",
    loginCFResource: "مرجع CF",
    loginTagline: "أسلحة، شخصيات، رتب، خرائط، فعاليات — كل اللي محتاجه عشان تتصدر.",
    loginEmailLabel: "البريد / الاسم / الهاتف",
    loginEmailPlaceholder: "أدخل بياناتك",
    loginPasswordLabel: "كلمة المرور",
    loginSigningIn: "جاري الدخول...",
    loginSignIn: "دخول",
    loginNoAccount: "مش عندك حساب؟",
    loginCreateOne: "أنشئ واحد",
    loginRankCalc: "حاسبة الرتب",
    loginArsenalDB: "قاعدة بيانات الأسلحة",
    loginLiveEvents: "فعاليات ومستجدات مباشرة",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

function getInitialLanguage(): Language {
  // 1. Check URL path — /ar prefix takes highest priority
  try {
    const path = window.location.pathname;
    if (path === "/ar" || path.startsWith("/ar/")) return "ar";
  } catch { }
  // 2. Check saved preference
  try {
    const saved = localStorage.getItem("language");
    if (saved === "ar" || saved === "en") return saved;
  } catch { }
  // 3. Auto-detect from browser locale
  try {
    const langs = navigator.languages || [navigator.language || ""];
    if (langs.some((l) => l.startsWith("ar"))) return "ar";
  } catch { }
  return "en";
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    // Update URL to reflect language change
    try {
      const path = window.location.pathname;
      const hash = window.location.hash;
      const search = window.location.search;
      const isArPath = path === "/ar" || path.startsWith("/ar/");
      const basePath = isArPath ? (path === "/ar" ? "/" : path.slice(3) || "/") : path;
      if (lang === "ar") {
        const newPath = basePath === "/" ? "/ar" : `/ar${basePath}`;
        window.history.replaceState(null, "", newPath + search + hash);
      } else {
        window.history.replaceState(null, "", basePath + search + hash);
      }
    } catch { }
  };

  useEffect(() => {
    const root = document.documentElement;
    root.setAttribute("lang", language);
    // ✅ Fix RTL: Arabic is right-to-left
    const dir = language === "ar" ? "rtl" : "ltr";
    root.setAttribute("dir", dir);
    document.body.setAttribute("dir", dir);

    if (language === "ar") {
      root.classList.add("font-arabic");
    } else {
      root.classList.remove("font-arabic");
      document.body.classList.remove("rtl");
    }

    localStorage.setItem("language", language);
  }, [language]);

  // Sync language when user navigates to /ar or away from it
  useEffect(() => {
    const handlePopState = () => {
      const path = window.location.pathname;
      const isAr = path === "/ar" || path.startsWith("/ar/");
      setLanguageState(isAr ? "ar" : (localStorage.getItem("language") as Language) || "en");
    };
    window.addEventListener("popstate", handlePopState);
    return () => window.removeEventListener("popstate", handlePopState);
  }, []);

  const toggleLanguage = () => {
    setLanguage(language === "en" ? "ar" : "en");
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
