import { createContext, useContext, useEffect, useState } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    about: "About",
    contact: "Contact",
    categories: "Categories",
    all: "All",
    news: "News",
    reviews: "Reviews",
    tutorials: "Tutorials",
    videos: "Videos",
    events: "Events",
    search: "Search articles...",
    readMore: "Read More",
    recentPosts: "Recent Posts",
    popularTags: "Popular Tags",
    mostViewed: "Most Viewed",
    wikiPicks: "CrossFire Wiki Picks",
    readingTime: "min read",
    views: "views",
    latest: "Latest",
    popular: "Popular",
    featured: "Featured",
    relatedArticles: "Related Articles",
    comments: "Comments",
    addComment: "Add a comment",
    submit: "Submit",
    admin: "Admin Dashboard",
    logout: "Logout",
    login: "Login",
    signUp: "Sign Up",
    copyright: "© 2025 CrossFire Wiki — All Rights Reserved",
    loading: "Loading...",
    newsNotFound: "News Not Found",
    backToNews: "Back to News",
    readMoreNews: "Read More News",
    newsAndUpdates: "News & Updates",
    translationNote: "Translation Note:",
    translationNoteText: "An Arabic version may be available for this article. Use the language control to switch between versions.",
    mercenaries: "Mercenaries",
    mercenariesSubtitle: "Playable characters, roles, and profiles.",
    graveGames: "GRAVE GAMES",
    graveGamesSubtitle: "The Spider's Web Awaits",
    eventDescription: "An archived Halloween event featuring missions and time-limited rewards.",
    eventDetails: "This archive records the event's objectives, reward types, and dates. Details are preserved for reference and may not reflect current availability.",
    eventFeatures: "Event Features",
    eventFeature1: "Complete daily and weekly challenges",
    eventFeature2: "Review the recorded Halloween rewards",
    eventFeature3: "Check the documented character and weapon items",
    eventFeature4: "Track your progress through the event portal",
    eventFeature5: "Compare the event's recorded progression requirements",
    limitedTimeOnly: "Event Archive",
    limitedTimeText: "The dates shown are historical. Check current announcements for live events and available rewards.",
    aboutWiki: "About CrossFire Wiki",
    aboutWelcome: "CrossFire Wiki is an independent community reference for CrossFire news, game systems, weapons, characters, and updates.",
    ourMission: "Our Mission",
    missionText: "We document CrossFire systems and maintain clear references for players. Pages cover basic terms, item data, events, and practical guides, with source notes where available.",
    whatWeCover: "What We Cover",
    coverItem1: "CrossFire game news and updates",
    coverItem2: "Character guides and mercenary profiles",
    coverItem3: "Weapon reviews and gameplay tips",
    coverItem4: "Community events and tournaments",
    coverItem5: "Game modes and strategy guides",
    joinCommunity: "Join Our Community",
    communityText: "Share corrections, report outdated information, and discuss the game with other CrossFire players through the community channels.",
    contactUs: "Contact Us",
    contactSubtitle: "Send a question, correction, or suggestion and include enough detail for us to investigate it.",
    email: "Email",
    chat: "Chat",
    liveChatSupport: "Live chat support",
    notFound: "404 Page Not Found",
    notFoundText: "This page doesn't exist or may have been removed.",
    backToHome: "Go back home",
    eventInformation: "Event Information",
    theSpidersWeb: "The Spider's Web",
    eventDates: "October 1 - 31, 2025",
    loginToCheckProgress: "Login to Check Your Progress",
    social: "Social",
    followUsOnline: "Follow us online",
    sendUsMessage: "Send us a message",
    name: "Name",
    yourName: "Your name",
    yourEmail: "your@email.com",
    message: "Message",
    tellUsWhatsOnYourMind: "Tell us what's on your mind...",
    eventNotFound: "Event Not Found",
    back: "Back",
    upcoming: "Upcoming",
    trending: "Trending",
    showOriginal: "Show Original",
    showTranslation: "Show Translation",
    viewingTranslation: "You are viewing the translated version",
    translationAvailable: "Translation available - click the button above to switch",
    explore: "Explore",
    modes: "Modes",
    maps: "Maps",
    ranks: "Ranks",
    weapons: "Weapons",
    posts: "Posts",
    blog: "Blog",
    support: "Support",
    pricing: "Pricing",
    sellers: "Sellers",
    supportTickets: "Support Tickets",
    createTicket: "Create Ticket",
    download: "Download",
    noArticlesFound: "No articles found",
    faq: "FAQ",
    faqFull: "Frequently Asked Questions",
    faqSubtitle: "Find answers to the most common questions about CrossFire.",
    faqSearch: "Search questions...",
    faqNoResults: "No results found. Try different keywords.",
    faqStillNeedHelp: "Still can't find your answer?",
    faqContactPrompt: "Our support team is here to help. Submit a ticket and we'll get back to you.",
    faqSubmitTicket: "Submit a Support Ticket",
    faqAllTopics: "All Topics",
    faqCategories: "FAQ Categories",
    faqManage: "Manage FAQ",
    faqAddCategory: "Add Category",
    faqEditCategory: "Edit Category",
    faqDeleteCategory: "Delete Category",
    faqAddQuestion: "Add Question",
    faqEditQuestion: "Edit Question",
    faqDeleteQuestion: "Delete Question",
    faqCategoryName: "Category Name",
    faqCategoryNameAr: "Category Name (Arabic)",
    faqQuestion: "Question",
    faqQuestionAr: "Question (Arabic)",
    faqAnswer: "Answer",
    faqAnswerAr: "Answer (Arabic)",

    tableOfContents: "Table of Contents",
    quickTips: "Quick Tips",
    backToTop: "Back to top",
    countdown: "Countdown",
    eventStatus: "Event status",
    published: "Published",
    currentLanguage: "Language",
    headingsPlaceholder: "Headings will appear here when the event content includes sections.",
    eventDatePending: "Event date will be updated soon",
    eventLiveOrEnded: "Event is live or already ended",
    navNews: "NEWS",
    navGame: "GAME",
    navShop: "SHOP",
    navCommunity: "COMMUNITY",
    navSupport: "SUPPORT",
    navUpdates: "Updates",
    navGameOverview: "Game Overview",
    navModes: "Modes",
    navMaps: "Maps",
    navWeapons: "Weapons",
    navMercenaries: "Mercenaries",
    navRankings: "Rankings",
    navDownload: "Download",
    navSellers: "Sellers",
    navServices: "Services",
    navBrowseItems: "Browse Items",
    navForum: "Forum",
    navAI: "AI Assistant",
    navReviews: "Reviews",
    navContact: "Contact",
    navFAQ: "FAQ",
    navSubmitTicket: "Submit Ticket",
    navMyTickets: "My Tickets",
    navProfile: "Profile",
    navLogout: "Logout",
    navEvents: "Events",
    navVideos: "Videos",
    searchPlaceholder: "Search...",
    downloadNow: "Download Now",
    downloadCrossFire: "Download CrossFire",
    latestAnnouncements: "Latest announcements",
    officialInstaller: "Official installer",
    officialInstallerDesc: "Download the latest CrossFire installer from the official Z8Games page to avoid broken or outdated mirrors.",
    checkUpdatesFirst: "Check updates first",
    checkUpdatesDesc: "Review current announcements and patch notes before reinstalling so you know whether maintenance or launcher updates are active.",
    useEnoughStorage: "Use enough storage",
    useEnoughStorageDesc: "Keep extra free disk space available for updates, anticheat files, and temporary installer extraction.",
    systemRequirements: "System Requirements",
    readyToJoin: "Ready to join the battle?",
    readyToJoinDesc: "Download CrossFire now and experience intense multiplayer action. Check the system requirements above to ensure your PC meets the minimum specifications.",
    minimum: "Minimum:",
    recommended: "Recommended:",
    leaveComment: "Leave a Comment",
    yourNameRequired: "Your name (Required)",
    emailOptional: "Email (Optional)",
    writeComment: "Write your comment...",
    replyTo: "Reply to",
    submitReply: "Submit Reply",
    cancel: "Cancel",
    deleteComment: "Delete",
    reply: "Reply",
    beFirstToComment: "Be the first to comment!",
    commentPosted: "Comment posted!",
    failedToPost: "Failed to post",

    // Header
    navTutorials: "Tutorials",

    // Footer
    footerStayInformed: "Stay Informed",
    footerNewsEventsTitle: "CrossFire News & Events",
    footerNewsletterSubtitle: "Weekly digest of updates, tournaments and guides.",
    footerEmailPlaceholder: "Your email address",
    footerSubscribe: "Subscribe",
    footerSubscribed: "Subscribed!",
    footerBackToTop: "BACK TO TOP",
    footerNewsSection: "NEWS",
    footerGameSection: "GAME",
    footerCommunitySection: "COMMUNITY",
    footerShopSection: "SHOP",
    footerSupportSection: "SUPPORT",
    footerFollowSection: "FOLLOW CROSSFIRE",
    footerLatestNews: "Latest News",
    footerUpdates: "Updates",
    footerGameOverview: "Game Overview",
    footerGameModes: "Game Modes",
    footerForumPosts: "Forum / Posts",
    footerTutorials: "Tutorials",
    footerContactUs: "Contact Us",
    footerSellersMarket: "Sellers Market",
    footerCommunityReviews: "Community Reviews",
    footerSubmitTicket: "Submit Ticket",
    footerMyTickets: "My Tickets",
    footerJoinCommunity: "JOIN COMMUNITY",
    footerWhatsappChannel: "WhatsApp Channel",
    footerPlayNow: "PLAY NOW",
    footerDownloadCF: "Download CrossFire",
    footerPrivacy: "Privacy",
    footerTerms: "Terms",

    // Support page
    supportCenter: "Support Center",
    supportSubmitTitle: "Submit a Ticket",
    supportNeedHelp: "Need help? Fill out the form below and our team will get back to you.",
    supportJoinWhatsapp: "Join our WhatsApp channel for updates and quick community support.",
    supportOpenChannel: "Open Channel",
    supportResponseTime: "Response Time",
    supportEmailUpdates: "Email Updates",
    supportTrackStatus: "Track Status",
    supportAutoNotify: "Auto-notify",
    supportMyTickets: "My Tickets",
    supportTicketSuccess: "Ticket submitted successfully! Check your email for updates.",
    supportTicketFormTitle: "Support Ticket Form",
    supportAllRequired: "All fields are required unless marked optional.",
    supportYourName: "Your Name",
    supportEmailAddress: "Email Address",
    supportCategory: "Category",
    supportSelectCategory: "Select a category",
    supportCategoryTech: "Technical Issue",
    supportCategoryAccount: "Account Support",
    supportCategoryBilling: "Billing Question",
    supportCategoryFeature: "Feature Request",
    supportCategoryBug: "Bug Report",
    supportCategoryOther: "Other",
    supportPriority: "Priority",
    supportSelectPriority: "Select priority",
    supportLow: "Low",
    supportNormal: "Normal",
    supportHigh: "High",
    supportSubject: "Subject",
    supportSubjectPlaceholder: "Brief description of your issue",
    supportDescription: "Description",
    supportDescriptionPlaceholder: "Please provide detailed information about your issue...",
    supportAttachment: "Attachment (optional)",
    supportUploadImage: "Upload Screenshot or Image",
    supportImageUploaded: "Image uploaded — it will be included with your ticket.",
    supportSubmitting: "Submitting…",
    supportSubmitBtn: "Submit Ticket",
    supportTicketToast: "Ticket Submitted",
    supportTicketToastDesc: "Your support ticket has been submitted. We'll get back to you soon!",
    supportErrorToast: "Error",
    supportBreadcrumbHome: "Home",

    // Contact page
    contactGetInTouch: "Get In Touch",
    contactSubtitleFull: "Have a question, suggestion, or want to contribute? We'd love to hear from you.",
    contactEmailTitle: "Email",
    contactEmailDesc: "Response within 24–48 hours",
    contactTicketTitle: "Support Ticket",
    contactTicketValue: "Official support system",
    contactTicketDesc: "Submit and track your request",
    contactWhatsappValue: "Join WhatsApp updates",
    contactWhatsappDesc: "News, alerts, and community support",
    contactMessageSent: "Message Sent!",
    contactMessageSentDesc: "We'll get back to you within 24–48 hours.",
    contactFailedSend: "Failed to send. Please try again or email us directly.",
    contactSending: "Sending…",
    contactFollowUs: "Follow Us",
    contactNeedSupport: "Need Support?",
    contactNeedSupportDesc: "For account issues, bugs, or ZP seller disputes, submit an official ticket.",
    contactSubmitTicketBtn: "Submit Ticket",

    // Login page
    loginTitle: "Sign In",
    loginWelcome: "Welcome back to CrossFire Wiki",
    loginCFResource: "CF Resource",
    loginTagline: "Weapons, characters, ranks, maps, and events — organized in one searchable reference.",
    loginEmailLabel: "Email / Username / Phone",
    loginEmailPlaceholder: "Enter your identifier",
    loginPasswordLabel: "Password",
    loginSigningIn: "Signing In...",
    loginSignIn: "Sign In",
    loginNoAccount: "Don't have an account?",
    loginCreateOne: "Create one",
    loginRankCalc: "Rank Progression Calculator",
    loginArsenalDB: "Full Arsenal Database",
    loginLiveEvents: "Live Events & Updates",

    // Home page
    exploreTheWiki: "Browse the Wiki",
    categoryPortals: "Category Portals",
    jumpToAnySection: "Jump to any section",
    browse: "Browse",
    heroSearchBtn: "Search",
    heroSearchPlaceholder: "Search weapons, maps, mercenaries, modes...",
    eventSpotlight: "Event Spotlight",
    recentEvents: "Recent Events",
    newsUpdatesTitle: "News & Updates",
    archiveEyebrow: "Archive",
    monthlyHighlights: "Monthly Highlights",
    officialStaffEyebrow: "Official Staff",
    gameMasters: "Game Masters",
    viewAll: "View all",
    viewEvent: "View Event",
    featuredEventBadge: "Featured Event",
    onThisWiki: "On This Wiki",
    onThisWikiDesc: "CrossFire Wiki is an independent community reference for weapons, maps, ranks, characters, events, and game systems.",
    didYouKnow: "Did You Know?",
    quickNavigation: "Quick Navigation",
    communityLabel: "Community",
    joinOurDiscord: "Join our Discord",
    activePlayersCount: "Community discussion and support",
    joinNow: "Join Now",
    liveChat: "Live Chat",
    rankCalculator: "Rank Calculator",
    weaponDatabase: "Weapon Database",
    allGameModes: "All Game Modes",
    eventCalendar: "Event Calendar",
    communityReviewsLabel: "Community Reviews",
    supportCenterLabel: "Support Center",
    portalWeaponsDesc: "Rifles, pistols, snipers & melee",
    portalMapsDesc: "Battle arenas and layouts",
    portalMercenariesDesc: "Playable characters and profiles",
    portalModesDesc: "Every mode with strategies",
    portalRanksDesc: "Rank tiers, EXP & progression",
    portalEventsDesc: "Tournaments & limited-time ops",

    // Search page
    searchWikiTitle: "Search Wiki",
    searchInputPlaceholder: "Search weapons, maps, events, ranks...",
    searchTabWiki: "Wiki",
    searchTabArticles: "News & Posts",
    searchPrev: "← Prev",
    searchNext: "Next →",
    searchNoResultsFor: "No results for",
    searchTryDifferent: "Try a different term or browse the wiki categories",
    searchStartTyping: "Start typing to search the wiki",
    searchPageLabel: "Page",

    // Pricing page
    pricingGuideLabel: "ZP Pricing Guide",
    pricingPackagesTitle: "CrossFire ZP Packages",
    pricingSubheading: "Package references, spending notes, and safer top-up guidance.",
    pricingPackagesSection: "ZP Package Prices",
    pricingPackagesSub: "USD (approximate)",
    pricingMostPopular: "Most Popular",
    zpPointsLabel: "ZEN POINTS",
    pricingBuyBtn: "Buy on Z8Games",
    pricingPriceNote: "Prices are approximate and may vary by region. Always verify on the official Z8Games store.",
    pricingTopUpSection: "Where to Top Up",
    pricingVisitSellers: "Visit Sellers",
    pricingVisitSite: "Visit Site",
    pricingWhatBuySection: "What Can ZP Buy?",
    pricingPromoSection: "Promo Codes & Free ZP",
    pricingPromoNote: "CrossFire occasionally releases promo codes through official channels. Check regularly for free ZP and bonus items.",
    pricingCodesExpireNote: "Codes expire fast — follow our Discord and news page for the latest drops.",
    pricingStaySafe: "Stay Safe When Buying ZP",
    pricingBonus: "bonus",
    pricingSafeTip1: "Use the official Z8Games store or compare community sellers with clearly disclosed reviews and contact details.",
    pricingSafeTip2: "Never share your account password with anyone claiming to sell ZP.",
    pricingSafeTip3: "Z8Games staff and GMs will NEVER ask for your ZP or account access.",
    pricingSafeTip4: "If a deal sounds too good to be true, pause and check the provider's identity, contact details, and review history.",
    pricingSafeTip5: "Read the seller information and review signals before contacting a provider.",
    zpUsePermanentWeapons: "Permanent Weapons",
    zpUseSkins: "Character Skins",
    zpUseVVIP: "VVIP Weapons",
    zpUseCrateKeys: "Crate Keys",
    zpUseBoosts: "GP Boosts",
    zpUseAmmo: "Special Ammo",
    zpUseBlackMarket: "Black Market",
    zpUseMercRentals: "Mercenary Rentals",
    zpUsePermanentWeaponsDesc: "Permanent weapon options listed by the game.",
    zpUseSkinsDesc: "Exclusive appearance customization.",
    zpUseVVIPDesc: "Permanent weapons with special effects.",
    zpUseCrateKeysDesc: "Keys used to open the game's item crates.",
    zpUseBoostsDesc: "Items that can affect GP earnings according to game rules.",
    zpUseAmmoDesc: "Explosive, incendiary and special ammo.",
    zpUseBlackMarketDesc: "Limited-time exclusive spinning items.",
    zpUseMercRentalsDesc: "Rent premium mercenaries for 7–30 days.",

    // Privacy page
    privacyTitle: "Privacy Policy",
    privacyLastUpdated: "Last updated: March 26, 2026",
    privacyIntro: "Your privacy matters to us. This page explains what data we collect, why we collect it, and the controls you have over your information.",
    privacyCopyrightLine: "© 2026 CrossFire Wiki. All rights reserved.",
    privacyQuestionsText: "Questions about this Privacy Policy?",
    privSec1Title: "Information We Collect",
    privSec1Desc: "We collect information you provide directly to us when you:",
    privSec1i1: "Create an account or submit support tickets",
    privSec1i2: "Contact us through our support system",
    privSec1i3: "Participate in community features",
    privSec1i4: "Use our website and services",
    privSec2Title: "How We Use Your Information",
    privSec2Desc: "We use the information we collect to:",
    privSec2i1: "Provide, maintain, and improve our services",
    privSec2i2: "Process and respond to support requests",
    privSec2i3: "Send technical notices and support messages",
    privSec2i4: "Monitor and analyze usage patterns and trends",
    privSec3Title: "Data Security",
    privSec3Desc: "We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. No method of transmission over the internet is 100% secure, but we strive to use commercially acceptable means.",
    privSec4Title: "Cookies & Tracking",
    privSec4Desc: "We use cookies and similar technologies to enhance your experience. You can control cookie settings through your browser. We may use analytics services (Google Analytics) to understand how our website is used.",
    privSec5Title: "Your Rights",
    privSec5Desc: "Depending on your location, you may have rights regarding your personal data:",
    privSec5i1: "Access to your personal information",
    privSec5i2: "Correction of inaccurate information",
    privSec5i3: "Deletion of your personal information",
    privSec5i4: "Restriction or objection to processing",
    privSec5i5: "Data portability",
    privSec6Title: "Information Sharing",
    privSec6Desc: "We do not sell or trade your personal information. We may share information when:",
    privSec6i1: "Service providers who help operate our website",
    privSec6i2: "Required by law or to protect our rights",
    privSec6i3: "In connection with a business transfer",
    privSec7Title: "Children's Privacy",
    privSec7Desc: "Our services are not intended for children under 13. We do not knowingly collect personal information from children under 13. If we become aware of such data, we will delete it promptly.",
    privSec8Title: "Changes to This Policy",
    privSec8Desc: "We may update this Privacy Policy from time to time. We will notify you of changes by posting the new policy on this page and updating the \"Last updated\" date at the top.",

    // Terms page
    termsTitle: "Terms of Service",
    termsLastUpdated: "Last updated: March 26, 2026",
    termsIntro: "These terms explain your rights and responsibilities when using CrossFire Wiki. By continuing to browse, register, or submit content, you agree to follow this policy.",
    termsCopyrightLine: "© 2026 CrossFire Wiki. All rights reserved.",
    termsQuestionsText: "Questions about these Terms of Service?",
    termsSec1Title: "Acceptance of Terms",
    termsSec1Desc: "By accessing and using CrossFire Wiki (crossfire.wiki), you accept and agree to be bound by the terms of this agreement. If you do not agree, please do not use this service.",
    termsSec2Title: "User Responsibilities",
    termsSec2i1: "Provide accurate and truthful information when creating accounts or submitting content",
    termsSec2i2: "Respect intellectual property rights of others",
    termsSec2i3: "Not engage in harassment, spam, or abusive behavior",
    termsSec2i4: "Follow CrossFire's terms of service and community guidelines",
    termsSec2i5: "Not attempt to circumvent security measures or access restricted areas",
    termsSec3Title: "Content Guidelines",
    termsSec3Desc: "All content on CrossFire Wiki must adhere to the following:",
    termsSec3i1: "Content must be relevant to CrossFire gaming",
    termsSec3i2: "No hate speech, discrimination, or offensive material",
    termsSec3i3: "Respect copyright and fair use policies",
    termsSec3i4: "Provide accurate information to the best of your ability",
    termsSec3i5: "Credit sources when applicable",
    termsSec4Title: "Intellectual Property",
    termsSec4Desc: "CrossFire Wiki content is protected by copyright and trademark laws. CrossFire® is a registered trademark of Smilegate. All game-related content, images, and materials belong to their respective owners. CrossFire Wiki provides informational content for educational purposes only.",
    termsSec5Title: "Disclaimer",
    termsSec5Desc: "The information provided on CrossFire Wiki is for general informational purposes only. While we strive for accuracy, we cannot guarantee the completeness or timeliness of information. Use of this website is at your own risk.",
    termsSec6Title: "Changes to Terms",
    termsSec6Desc: "We reserve the right to modify these terms at any time. Changes will be effective immediately upon posting on this page. Your continued use of the service constitutes acceptance of the modified terms.",
  },
  ar: {
    home: "الرئيسية",
    about: "من نحن",
    contact: "اتصل بنا",
    categories: "التصنيفات",
    all: "الكل",
    news: "أخبار",
    reviews: "مراجعات",
    tutorials: "دروس",
    videos: "فيديوهات",
    events: "فعاليات",
    search: "ابحث عن المقالات...",
    readMore: "اقرأ المزيد",
    recentPosts: "آخر المقالات",
    popularTags: "الوسوم الشائعة",
    mostViewed: "الأكثر مشاهدة",
    wikiPicks: "اختيارات CrossFire Wiki",
    readingTime: "دقيقة قراءة",
    views: "مشاهدة",
    latest: "الأحدث",
    popular: "الأكثر شعبية",
    featured: "مميز",
    relatedArticles: "مقالات ذات صلة",
    comments: "التعليقات",
    addComment: "أضف تعليقاً",
    submit: "إرسال",
    admin: "لوحة الإدارة",
    logout: "تسجيل الخروج",
    login: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    copyright: "© 2025 CrossFire Wiki — جميع الحقوق محفوظة",
    loading: "جاري التحميل...",
    newsNotFound: "الخبر غير موجود",
    backToNews: "العودة للأخبار",
    readMoreNews: "اقرأ المزيد من الأخبار",
    newsAndUpdates: "الأخبار والتحديثات",
    translationNote: "ملاحظة الترجمة:",
    translationNoteText: "قد تتوفر نسخة عربية من هذا المقال. استخدم أداة اللغة للتبديل بين النسختين.",
    mercenaries: "الشخصيات",
    mercenariesSubtitle: "الشخصيات القابلة للعب وأدوارها وملفاتها.",
    graveGames: "ألعاب القبور",
    graveGamesSubtitle: "شبكة العنكبوت في الانتظار",
    eventDescription: "أرشيف فعالية هالوين يتضمن مهاماً ومكافآت محدودة المدة.",
    eventDetails: "يوثق هذا الأرشيف أهداف الفعالية وأنواع المكافآت ومواعيدها. قد لا تعكس التفاصيل ما هو متاح حالياً.",
    eventFeatures: "ميزات الحدث",
    eventFeature1: "أكمل التحديات اليومية والأسبوعية",
    eventFeature2: "راجع المكافآت المسجلة للفعالية",
    eventFeature3: "راجع عناصر الشخصيات والأسلحة المذكورة",
    eventFeature4: "تتبع تقدمك عبر بوابة الحدث",
    eventFeature5: "قارن متطلبات التقدم المسجلة للفعالية",
    limitedTimeOnly: "أرشيف فعالية",
    limitedTimeText: "المواعيد المعروضة تاريخية. راجع الإعلانات الحالية لمعرفة الفعاليات والمكافآت المتاحة الآن.",
    aboutWiki: "عن CrossFire Wiki",
    aboutWelcome: "كروس فاير ويكي مرجع مجتمعي مستقل لأخبار اللعبة وأنظمتها وأسلحتها وشخصياتها وتحديثاتها.",
    ourMission: "مهمتنا",
    missionText: "نوثق أنظمة CrossFire وننظم المراجع بطريقة واضحة للاعبين. تغطي الصفحات المصطلحات الأساسية وبيانات العناصر والفعاليات والأدلة العملية، مع ذكر المصادر عند توفرها.",
    whatWeCover: "ما نغطيه",
    coverItem1: "أخبار وتحديثات لعبة CrossFire",
    coverItem2: "أدلة الشخصيات وملفات المرتزقة",
    coverItem3: "مراجعات الأسلحة ونصائح اللعب",
    coverItem4: "الفعاليات المجتمعية والبطولات",
    coverItem5: "أوضاع اللعب وأدلة الاستراتيجيات",
    joinCommunity: "انضم إلى مجتمعنا",
    communityText: "شارك التصحيحات وأبلغ عن المعلومات القديمة وناقش اللعبة مع اللاعبين الآخرين عبر قنوات المجتمع.",
    contactUs: "اتصل بنا",
    contactSubtitle: "أرسل سؤالك أو تصحيحك أو اقتراحك مع التفاصيل التي تساعدنا على مراجعته.",
    email: "البريد الإلكتروني",
    chat: "الدردشة",
    liveChatSupport: "دعم الدردشة المباشرة",
    notFound: "الصفحة غير موجودة 404",
    notFoundText: "هذه الصفحة غير موجودة أو ربما تمت إزالتها.",
    backToHome: "العودة للصفحة الرئيسية",
    eventInformation: "معلومات الحدث",
    theSpidersWeb: "شبكة العنكبوت",
    eventDates: "1 - 31 أكتوبر 2025",
    loginToCheckProgress: "تسجيل الدخول لمتابعة تقدمك",
    social: "التواصل الاجتماعي",
    followUsOnline: "تابعنا عبر الإنترنت",
    sendUsMessage: "أرسل لنا رسالة",
    name: "الاسم",
    yourName: "اسمك",
    yourEmail: "بريدك@الإلكتروني.com",
    message: "الرسالة",
    tellUsWhatsOnYourMind: "أخبرنا بما يدور في ذهنك...",
    eventNotFound: "الحدث غير موجود",
    back: "رجوع",
    upcoming: "قادم",
    trending: "رائج",
    showOriginal: "عرض النص الأصلي",
    showTranslation: "عرض الترجمة",
    viewingTranslation: "أنت تشاهد النسخة المترجمة",
    translationAvailable: "الترجمة متوفرة - انقر الزر أعلاه للتبديل",
    explore: "استكشف",
    modes: "الأوضاع",
    maps: "الخرائط",
    ranks: "الرتب",
    weapons: "الأسلحة",
    posts: "المقالات",
    blog: "المدونة",
    support: "الدعم",
    pricing: "التسعير",
    sellers: "البائعون",
    supportTickets: "تذاكر الدعم",
    createTicket: "إنشاء تذكرة",
    download: "تحميل",
    noArticlesFound: "لم يتم العثور على مقالات",
    faq: "الأسئلة الشائعة",
    faqFull: "الأسئلة الشائعة",
    faqSubtitle: "لاقي إجابات على أكتر الأسئلة شيوعًا عن CrossFire.",
    faqSearch: "ابحث في الأسئلة...",
    faqNoResults: "مش لاقي نتايج. جرب كلمات تانية.",
    faqStillNeedHelp: "مش لاقي إجابتك؟",
    faqContactPrompt: "فريق الدعم بتاعنا موجود يساعدك. ابعتلنا تذكرة وهنرد عليك بسرعة.",
    faqSubmitTicket: "ابعت تذكرة ساببورت",
    faqAllTopics: "كل المواضيع",
    faqCategories: "تصنيفات الأسئلة",
    faqManage: "إدارة الأسئلة الشائعة",
    faqAddCategory: "إضافة تصنيف",
    faqEditCategory: "تعديل التصنيف",
    faqDeleteCategory: "حذف التصنيف",
    faqAddQuestion: "إضافة سؤال",
    faqEditQuestion: "تعديل السؤال",
    faqDeleteQuestion: "حذف السؤال",
    faqCategoryName: "اسم التصنيف",
    faqCategoryNameAr: "اسم التصنيف (عربي)",
    faqQuestion: "السؤال",
    faqQuestionAr: "السؤال (عربي)",
    faqAnswer: "الإجابة",
    faqAnswerAr: "الإجابة (عربي)",

    tableOfContents: "محتويات الصفحة",
    quickTips: "نصائح سريعة",
    backToTop: "العودة للأعلى",
    countdown: "العد التنازلي",
    eventStatus: "حالة الحدث",
    published: "تاريخ النشر",
    currentLanguage: "اللغة",
    headingsPlaceholder: "ستظهر العناوين هنا عندما يحتوي محتوى الحدث على أقسام واضحة.",
    eventDatePending: "سيتم تحديث الموعد قريباً",
    eventLiveOrEnded: "انتهى الحدث أو بدأ بالفعل",
    navNews: "الأخبار",
    navGame: "اللعبة",
    navShop: "المتجر",
    navCommunity: "المجتمع",
    navSupport: "الدعم",
    navUpdates: "التحديثات",
    navGameOverview: "نظرة عامة",
    navModes: "الأوضاع",
    navMaps: "الخرائط",
    navWeapons: "الأسلحة",
    navMercenaries: "الشخصيات",
    navRankings: "الرتب",
    navDownload: "تحميل",
    navSellers: "البائعون",
    navServices: "الخدمات",
    navBrowseItems: "تصفح العناصر",
    navForum: "منتدى المجتمع",
    navAI: "مساعد ذكي",
    navReviews: "المراجعات",
    navContact: "اتصل بنا",
    navFAQ: "الأسئلة الشائعة",
    navSubmitTicket: "رفع تذكرة",
    navMyTickets: "تذاكري",
    navProfile: "الملف الشخصي",
    navLogout: "تسجيل الخروج",
    navEvents: "الفعاليات",
    navVideos: "فيديوهات",
    searchPlaceholder: "ابحث...",
    downloadNow: "حمّل الآن",
    downloadCrossFire: "حمّل CrossFire",
    latestAnnouncements: "آخر الإعلانات",
    officialInstaller: "النسخة الرسمية",
    officialInstallerDesc: "حمّل أحدث نسخة من CrossFire من صفحة Z8Games الرسمية لتجنب النسخ المعطوبة أو القديمة.",
    checkUpdatesFirst: "تحقق من التحديثات أولاً",
    checkUpdatesDesc: "اطلع على الإعلانات وملاحظات التحديثات قبل إعادة التثبيت حتى تعرف إذا كان هناك صيانة أو تحديثات للمشغل.",
    useEnoughStorage: "تأكد من مساحة التخزين",
    useEnoughStorageDesc: "احتفظ بمساحة قرص حرة كافية للتحديثات وملفات مكافحة الغش واستخراج المثبت المؤقت.",
    systemRequirements: "متطلبات التشغيل",
    readyToJoin: "مستعد للانضمام للمعركة؟",
    readyToJoinDesc: "حمّل CrossFire الآن وعش تجربة لعب جماعي مكثف. تحقق من متطلبات التشغيل أعلاه للتأكد أن جهازك يلبي المواصفات الدنيا.",
    minimum: "الحد الأدنى:",
    recommended: "موصى به:",
    leaveComment: "اترك تعليقاً",
    yourNameRequired: "اسمك (مطلوب)",
    emailOptional: "البريد الإلكتروني (اختياري)",
    writeComment: "اكتب تعليقك...",
    replyTo: "رد على",
    submitReply: "إرسال الرد",
    cancel: "إلغاء",
    deleteComment: "حذف",
    reply: "رد",
    beFirstToComment: "كن أول من يعلق!",
    commentPosted: "تم نشر التعليق!",
    failedToPost: "فشل في النشر",

    // Header
    navTutorials: "الدروس",

    // Footer
    footerStayInformed: "ابقَ على اطلاع",
    footerNewsEventsTitle: "أخبار وفعاليات CrossFire",
    footerNewsletterSubtitle: "ملخص أسبوعي للتحديثات والبطولات والأدلة.",
    footerEmailPlaceholder: "بريدك الإلكتروني",
    footerSubscribe: "اشترك",
    footerSubscribed: "تم الاشتراك!",
    footerBackToTop: "العودة للأعلى",
    footerNewsSection: "الأخبار",
    footerGameSection: "اللعبة",
    footerCommunitySection: "المجتمع",
    footerShopSection: "المتجر",
    footerSupportSection: "الدعم",
    footerFollowSection: "تابع CrossFire",
    footerLatestNews: "آخر الأخبار",
    footerUpdates: "التحديثات",
    footerGameOverview: "نظرة عامة على اللعبة",
    footerGameModes: "أوضاع اللعب",
    footerForumPosts: "المنتدى والمقالات",
    footerTutorials: "الدروس",
    footerContactUs: "اتصل بنا",
    footerSellersMarket: "سوق البائعين",
    footerCommunityReviews: "تقييمات المجتمع",
    footerSubmitTicket: "رفع تذكرة",
    footerMyTickets: "تذاكري",
    footerJoinCommunity: "انضم للمجتمع",
    footerWhatsappChannel: "قناة واتساب",
    footerPlayNow: "العب الآن",
    footerDownloadCF: "حمّل CrossFire",
    footerPrivacy: "الخصوصية",
    footerTerms: "الشروط",

    // Support page
    supportCenter: "مركز الدعم",
    supportSubmitTitle: "ارفع تذكرة",
    supportNeedHelp: "محتاج مساعدة؟ املأ الفورم وفريقنا هيرد عليك.",
    supportJoinWhatsapp: "انضم لقناة واتساب بتاعتنا للتحديثات والدعم السريع.",
    supportOpenChannel: "افتح القناة",
    supportResponseTime: "وقت الرد",
    supportEmailUpdates: "تحديثات البريد",
    supportTrackStatus: "تتبع الحالة",
    supportAutoNotify: "تلقائي",
    supportMyTickets: "تذاكري",
    supportTicketSuccess: "تم رفع التذكرة بنجاح! تحقق من بريدك للتحديثات.",
    supportTicketFormTitle: "فورم تذكرة الدعم",
    supportAllRequired: "كل الحقول مطلوبة إلا اللي مكتوب عليها اختياري.",
    supportYourName: "اسمك",
    supportEmailAddress: "البريد الإلكتروني",
    supportCategory: "التصنيف",
    supportSelectCategory: "اختار تصنيف",
    supportCategoryTech: "مشكلة تقنية",
    supportCategoryAccount: "دعم الحساب",
    supportCategoryBilling: "سؤال عن الفواتير",
    supportCategoryFeature: "طلب ميزة",
    supportCategoryBug: "بلاغ باج",
    supportCategoryOther: "أخرى",
    supportPriority: "الأولوية",
    supportSelectPriority: "اختار الأولوية",
    supportLow: "منخفض",
    supportNormal: "عادي",
    supportHigh: "عالي",
    supportSubject: "الموضوع",
    supportSubjectPlaceholder: "وصف مختصر للمشكلة",
    supportDescription: "التفاصيل",
    supportDescriptionPlaceholder: "اكتب تفاصيل المشكلة بالكامل...",
    supportAttachment: "مرفق (اختياري)",
    supportUploadImage: "ارفع سكرين شوت أو صورة",
    supportImageUploaded: "تم رفع الصورة — ستُرفق مع التذكرة.",
    supportSubmitting: "جاري الإرسال...",
    supportSubmitBtn: "ارفع التذكرة",
    supportTicketToast: "تم رفع التذكرة",
    supportTicketToastDesc: "تم إرسال تذكرة الدعم. هنرد عليك قريباً!",
    supportErrorToast: "خطأ",
    supportBreadcrumbHome: "الرئيسية",

    // Contact page
    contactGetInTouch: "تواصل معنا",
    contactSubtitleFull: "عندك سؤال أو اقتراح أو عايز تشارك؟ يسعدنا نسمع منك.",
    contactEmailTitle: "البريد الإلكتروني",
    contactEmailDesc: "رد خلال 24–48 ساعة",
    contactTicketTitle: "تذكرة دعم",
    contactTicketValue: "نظام الدعم الرسمي",
    contactTicketDesc: "ارفع وتابع طلبك",
    contactWhatsappValue: "انضم لتحديثات واتساب",
    contactWhatsappDesc: "أخبار وتنبيهات ودعم المجتمع",
    contactMessageSent: "تم إرسال الرسالة!",
    contactMessageSentDesc: "هنرد عليك خلال 24–48 ساعة.",
    contactFailedSend: "فشل الإرسال. جرب تاني أو راسلنا على البريد مباشرة.",
    contactSending: "جاري الإرسال...",
    contactFollowUs: "تابعنا",
    contactNeedSupport: "محتاج دعم؟",
    contactNeedSupportDesc: "لمشاكل الحساب أو الباج أو نزاعات البائعين، ارفع تذكرة رسمية.",
    contactSubmitTicketBtn: "ارفع تذكرة",

    // Login page
    loginTitle: "تسجيل الدخول",
    loginWelcome: "أهلاً بعودتك لـ CrossFire Wiki",
    loginCFResource: "مرجع CF",
    loginTagline: "الأسلحة والشخصيات والرتب والخرائط والفعاليات — في مرجع واحد قابل للبحث.",
    loginEmailLabel: "البريد / الاسم / الهاتف",
    loginEmailPlaceholder: "أدخل بياناتك",
    loginPasswordLabel: "كلمة المرور",
    loginSigningIn: "جاري الدخول...",
    loginSignIn: "دخول",
    loginNoAccount: "مش عندك حساب؟",
    loginCreateOne: "أنشئ واحد",
    loginRankCalc: "حاسبة الرتب",
    loginArsenalDB: "قاعدة بيانات الأسلحة",
    loginLiveEvents: "فعاليات ومستجدات مباشرة",

    // Home page
    exploreTheWiki: "تصفح الويكي",
    categoryPortals: "بوابات الأقسام",
    jumpToAnySection: "انتقل لأي قسم",
    browse: "تصفح",
    heroSearchBtn: "بحث",
    heroSearchPlaceholder: "ابحث عن أسلحة، خرائط، شخصيات، أوضاع...",
    eventSpotlight: "أبرز الفعاليات",
    recentEvents: "آخر الفعاليات",
    newsUpdatesTitle: "الأخبار والتحديثات",
    archiveEyebrow: "الأرشيف",
    monthlyHighlights: "أبرز الأحداث الشهرية",
    officialStaffEyebrow: "الطاقم الرسمي",
    gameMasters: "مشرفو اللعبة",
    viewAll: "عرض الكل",
    viewEvent: "عرض الفعالية",
    featuredEventBadge: "فعالية مميزة",
    onThisWiki: "في هذا الويكي",
    onThisWikiDesc: "كروس فاير ويكي مرجع مجتمعي مستقل للأسلحة والخرائط والرتب والشخصيات والفعاليات وأنظمة اللعب.",
    didYouKnow: "هل تعلم؟",
    quickNavigation: "تنقل سريع",
    communityLabel: "المجتمع",
    joinOurDiscord: "انضم إلى ديسكورد",
    activePlayersCount: "نقاشات ودعم من المجتمع",
    joinNow: "انضم الآن",
    liveChat: "دردشة مباشرة",
    rankCalculator: "حاسبة الرتب",
    weaponDatabase: "قاعدة بيانات الأسلحة",
    allGameModes: "جميع أوضاع اللعب",
    eventCalendar: "تقويم الفعاليات",
    communityReviewsLabel: "تقييمات المجتمع",
    supportCenterLabel: "مركز الدعم",
    portalWeaponsDesc: "بنادق، مسدسات، قناصة وسلاح أبيض",
    portalMapsDesc: "ساحات القتال والخرائط",
    portalMercenariesDesc: "الشخصيات القابلة للعب وملفاتها",
    portalModesDesc: "كل الأوضاع مع الاستراتيجيات",
    portalRanksDesc: "مستويات الرتب والتقدم",
    portalEventsDesc: "البطولات والعمليات المحدودة",

    // Search page
    searchWikiTitle: "بحث الويكي",
    searchInputPlaceholder: "ابحث عن أسلحة، خرائط، فعاليات، رتب...",
    searchTabWiki: "الويكي",
    searchTabArticles: "الأخبار والمقالات",
    searchPrev: "السابق →",
    searchNext: "← التالي",
    searchNoResultsFor: "لا نتائج لـ",
    searchTryDifferent: "جرب كلمة أخرى أو تصفح أقسام الويكي",
    searchStartTyping: "ابدأ الكتابة للبحث في الويكي",
    searchPageLabel: "صفحة",

    // Pricing page
    pricingGuideLabel: "دليل أسعار ZP",
    pricingPackagesTitle: "باقات ZP لـ CrossFire",
    pricingSubheading: "مراجع الباقات وملاحظات الإنفاق وإرشادات الشحن الآمن.",
    pricingPackagesSection: "أسعار باقات ZP",
    pricingPackagesSub: "دولار أمريكي (تقريبي)",
    pricingMostPopular: "الأكثر شعبية",
    zpPointsLabel: "ZEN POINTS",
    pricingBuyBtn: "اشتري من Z8Games",
    pricingPriceNote: "الأسعار تقريبية وقد تختلف حسب المنطقة. تحقق دائماً من متجر Z8Games الرسمي.",
    pricingTopUpSection: "من وين تشحن",
    pricingVisitSellers: "تصفح البائعين",
    pricingVisitSite: "زيارة الموقع",
    pricingWhatBuySection: "إيش يشتري ZP؟",
    pricingPromoSection: "كودات العروض وZP مجاناً",
    pricingPromoNote: "CrossFire يطلق كودات عروض أحياناً عبر القنوات الرسمية. تحقق بانتظام للحصول على ZP مجاناً وعناصر إضافية.",
    pricingCodesExpireNote: "الكودات تنتهي سريعاً — تابع ديسكوردنا وصفحة الأخبار لآخر العروض.",
    pricingStaySafe: "كن آمناً عند شراء ZP",
    pricingBonus: "بونص",
    pricingSafeTip1: "استخدم متجر Z8Games الرسمي أو قارن بين البائعين المجتمعيين مع مراجعات ووسائل اتصال واضحة.",
    pricingSafeTip2: "لا تشارك كلمة مرور حسابك مع أي شخص يدعي بيع ZP.",
    pricingSafeTip3: "موظفو Z8Games وGMs لن يطلبوا منك ZP أو الوصول لحسابك أبداً.",
    pricingSafeTip4: "إذا بدت الصفقة جيدة جداً لتكون حقيقية، توقف وتحقق من هوية البائع وبيانات التواصل وسجل المراجعات.",
    pricingSafeTip5: "اقرأ بيانات البائع ومؤشرات المراجعات قبل التواصل معه.",
    zpUsePermanentWeapons: "أسلحة دائمة",
    zpUseSkins: "سكنات الشخصيات",
    zpUseVVIP: "أسلحة VVIP",
    zpUseCrateKeys: "مفاتيح الصناديق",
    zpUseBoosts: "بوستات GP",
    zpUseAmmo: "ذخيرة خاصة",
    zpUseBlackMarket: "السوق السوداء",
    zpUseMercRentals: "إيجار شخصيات",
    zpUsePermanentWeaponsDesc: "خيارات الأسلحة الدائمة المدرجة في اللعبة.",
    zpUseSkinsDesc: "تخصيص مظهر حصري.",
    zpUseVVIPDesc: "أسلحة دائمة بمؤثرات خاصة.",
    zpUseCrateKeysDesc: "مفاتيح تستخدم لفتح صناديق العناصر داخل اللعبة.",
    zpUseBoostsDesc: "عناصر قد تؤثر في كسب GP وفقاً لقواعد اللعبة.",
    zpUseAmmoDesc: "ذخيرة انفجارية وحارقة وخاصة.",
    zpUseBlackMarketDesc: "عناصر حصرية محدودة الوقت.",
    zpUseMercRentalsDesc: "استأجر شخصيات مميزة لمدة 7-30 يوماً.",

    // Privacy page
    privacyTitle: "سياسة الخصوصية",
    privacyLastUpdated: "آخر تحديث: 26 مارس 2026",
    privacyIntro: "خصوصيتك تهمنا. هذه الصفحة تشرح البيانات التي نجمعها، وسبب جمعها، والتحكم الذي لديك في معلوماتك.",
    privacyCopyrightLine: "© 2026 CrossFire Wiki. جميع الحقوق محفوظة.",
    privacyQuestionsText: "أسئلة حول سياسة الخصوصية؟",
    privSec1Title: "المعلومات التي نجمعها",
    privSec1Desc: "نجمع المعلومات التي تقدمها لنا مباشرة عند:",
    privSec1i1: "إنشاء حساب أو رفع تذاكر دعم",
    privSec1i2: "التواصل معنا عبر نظام الدعم",
    privSec1i3: "المشاركة في ميزات المجتمع",
    privSec1i4: "استخدام موقعنا وخدماتنا",
    privSec2Title: "كيف نستخدم معلوماتك",
    privSec2Desc: "نستخدم المعلومات التي نجمعها من أجل:",
    privSec2i1: "تقديم خدماتنا والحفاظ عليها وتحسينها",
    privSec2i2: "معالجة طلبات الدعم والرد عليها",
    privSec2i3: "إرسال إشعارات تقنية ورسائل دعم",
    privSec2i4: "مراقبة وتحليل أنماط الاستخدام",
    privSec3Title: "أمان البيانات",
    privSec3Desc: "نطبق تدابير أمنية مناسبة لحماية معلوماتك الشخصية من الوصول غير المصرح به أو التعديل أو الإفصاح أو الإتلاف. لا توجد طريقة نقل عبر الإنترنت آمنة 100%، لكننا نسعى لاستخدام وسائل مقبولة تجارياً.",
    privSec4Title: "ملفات تعريف الارتباط والتتبع",
    privSec4Desc: "نستخدم ملفات تعريف الارتباط وتقنيات مماثلة لتحسين تجربتك. يمكنك التحكم في إعداداتها عبر متصفحك. قد نستخدم خدمات تحليل (Google Analytics) لفهم كيفية استخدام موقعنا.",
    privSec5Title: "حقوقك",
    privSec5Desc: "بحسب موقعك، قد تمتلك حقوقاً بشأن بياناتك الشخصية:",
    privSec5i1: "الوصول إلى معلوماتك الشخصية",
    privSec5i2: "تصحيح المعلومات غير الدقيقة",
    privSec5i3: "حذف معلوماتك الشخصية",
    privSec5i4: "تقييد أو الاعتراض على المعالجة",
    privSec5i5: "نقل البيانات",
    privSec6Title: "مشاركة المعلومات",
    privSec6Desc: "لا نبيع أو نتاجر بمعلوماتك الشخصية. قد نشارك المعلومات عند:",
    privSec6i1: "مزودي الخدمات الذين يساعدون في تشغيل موقعنا",
    privSec6i2: "عند الطلب القانوني أو لحماية حقوقنا",
    privSec6i3: "في سياق انتقال ملكية الأعمال",
    privSec7Title: "خصوصية الأطفال",
    privSec7Desc: "خدماتنا غير موجهة للأطفال دون 13 عاماً. لا نجمع معلومات شخصية من الأطفال عن قصد. إذا علمنا بوجود هذه البيانات سنحذفها فوراً.",
    privSec8Title: "التغييرات على هذه السياسة",
    privSec8Desc: "قد نحدث سياسة الخصوصية من وقت لآخر. سنخبرك بالتغييرات عبر نشر السياسة الجديدة على هذه الصفحة وتحديث تاريخ \"آخر تحديث\" في الأعلى.",

    // Terms page
    termsTitle: "شروط الخدمة",
    termsLastUpdated: "آخر تحديث: 26 مارس 2026",
    termsIntro: "هذه الشروط تشرح حقوقك ومسؤولياتك عند استخدام CrossFire Wiki. باستمرار التصفح أو التسجيل أو إرسال المحتوى، فأنت توافق على اتباع هذه السياسة.",
    termsCopyrightLine: "© 2026 CrossFire Wiki. جميع الحقوق محفوظة.",
    termsQuestionsText: "أسئلة حول شروط الخدمة؟",
    termsSec1Title: "قبول الشروط",
    termsSec1Desc: "بالوصول إلى CrossFire Wiki واستخدامها، فأنت توافق على الالتزام بشروط هذه الاتفاقية. إذا لم توافق، يرجى عدم استخدام الخدمة.",
    termsSec2Title: "مسؤوليات المستخدم",
    termsSec2i1: "تقديم معلومات دقيقة وصادقة عند إنشاء الحسابات أو إرسال المحتوى",
    termsSec2i2: "احترام حقوق الملكية الفكرية للآخرين",
    termsSec2i3: "عدم الانخراط في التحرش أو البريد العشوائي أو السلوك المسيء",
    termsSec2i4: "اتباع شروط خدمة CrossFire وإرشادات المجتمع",
    termsSec2i5: "عدم محاولة التحايل على التدابير الأمنية أو الوصول إلى المناطق المقيدة",
    termsSec3Title: "إرشادات المحتوى",
    termsSec3Desc: "يجب أن يلتزم جميع المحتوى في CrossFire Wiki بما يلي:",
    termsSec3i1: "يجب أن يكون المحتوى ذا صلة بألعاب CrossFire",
    termsSec3i2: "لا خطاب كراهية أو تمييز أو مواد مسيئة",
    termsSec3i3: "احترام سياسات حقوق النشر والاستخدام العادل",
    termsSec3i4: "تقديم معلومات دقيقة بأفضل ما يمكنك",
    termsSec3i5: "ذكر المصادر عند الاقتضاء",
    termsSec4Title: "الملكية الفكرية",
    termsSec4Desc: "محتوى CrossFire Wiki محمي بقوانين حقوق النشر والعلامات التجارية. CrossFire® علامة تجارية مسجلة لشركة Smilegate. جميع المحتوى والصور والمواد المتعلقة باللعبة تعود لأصحابها. يقدم CrossFire Wiki محتوى معلوماتياً لأغراض تعليمية فقط.",
    termsSec5Title: "إخلاء المسؤولية",
    termsSec5Desc: "المعلومات المقدمة في CrossFire Wiki لأغراض معلوماتية عامة فقط. بينما نسعى للدقة، لا نضمن اكتمال أو حداثة المعلومات. استخدام هذا الموقع على مسؤوليتك الخاصة.",
    termsSec6Title: "التغييرات على الشروط",
    termsSec6Desc: "نحتفظ بالحق في تعديل هذه الشروط في أي وقت. ستكون التغييرات سارية فور نشرها على هذه الصفحة. استمرار استخدامك للخدمة يُعد قبولاً للشروط المعدلة.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

function getInitialLanguage(): Language {
  // 1. Check URL path — /ar prefix takes highest priority
  let currentPath = "/";
  try {
    currentPath = window.location.pathname;
    if (currentPath === "/ar" || currentPath.startsWith("/ar/")) return "ar";
  } catch { }
  // The root route may honor a saved preference. Every named non-Arabic
  // route is canonical English and must not inherit stale Arabic state.
  if (currentPath !== "/" && currentPath !== "") return "en";
  // 2. Check saved preference
  try {
    const saved = localStorage.getItem("language");
    if (saved === "ar" || saved === "en") return saved;
  } catch { }
  // 3. Auto-detect from browser locale
  try {
    const langs = navigator.languages || [navigator.language || ""];
    if (langs.some((l) => l.startsWith("ar"))) return "ar";
  } catch { }
  return "en";
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    // Update URL to reflect language change
    try {
      const path = window.location.pathname;
      const hash = window.location.hash;
      const search = window.location.search;
      const isArPath = path === "/ar" || path.startsWith("/ar/");
      const basePath = isArPath ? (path === "/ar" ? "/" : path.slice(3) || "/") : path;
      if (lang === "ar") {
        const newPath = basePath === "/" ? "/ar" : `/ar${basePath}`;
        window.history.replaceState(null, "", newPath + search + hash);
      } else {
        window.history.replaceState(null, "", basePath + search + hash);
      }
    } catch { }
  };

  useEffect(() => {
    const root = document.documentElement;
    root.setAttribute("lang", language);
    // Keep layout direction always LTR — only text content changes per language
    root.setAttribute("dir", "ltr");
    document.body.setAttribute("dir", "ltr");

    if (language === "ar") {
      root.classList.add("font-arabic");
    } else {
      root.classList.remove("font-arabic");
      document.body.classList.remove("rtl");
    }

    localStorage.setItem("language", language);
  }, [language]);

  // Sync language when user navigates to /ar or away from it
  useEffect(() => {
    const handlePopState = () => {
      const path = window.location.pathname;
      const isAr = path === "/ar" || path.startsWith("/ar/");
      setLanguageState(isAr ? "ar" : "en");
    };
    window.addEventListener("popstate", handlePopState);
    return () => window.removeEventListener("popstate", handlePopState);
  }, []);

  const toggleLanguage = () => {
    setLanguage(language === "en" ? "ar" : "en");
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
